README.md
merge-runtime.js
package.json
withModuleFederation.js

use webpack data to feed runtime merging, depend less on hard-coded context

feat: Integrate context and improve runtime merging

---

README.md
bin/nextjs-mf.js

Turns out this works with 10.0.0.

Updating the CLI

---

patchSharing.js
react.js

Closes https://github.com/module-federation/nextjs-mf/pull/24#issuecomment-847089817

fix: isWebpack conditional - typeof fix

---

react.js
withModuleFederation.js

This fixes a typo in the plugin name and uses the unminified React version in development.

fix: Plugin typo, dev React version

---

README.md

The colin was missing when i tried to copy the example

add colin to the readme

---

demo/tmp/nextjs-mf/package.json
package.json
src/NextFederationPlugin.js
src/internal.js
yarn.lock

Use asset pipeline for emission

---

demo/3000-home/package.json
demo/3001-shop/next.config.js
demo/3001-shop/package.json
demo/3002-checkout/package.json
demo/tmp/nextjs-mf/package.json
demo/yarn.lock
package.json
src/NextFederationPlugin.js
src/internal.js
yarn.lock

Enabled optimization, prevent SWC from destroying remote container name

Enable Optimization in Child Compilers

---

packages/nextjs-mf/src/plugins/ChildFederationPlugin.ts

fix: SSR files not getting generated when enabled

---

apps/3000-home/next.config.js
apps/3000-home/project.json
apps/3001-shop/next.config.js
apps/3001-shop/pages/_app.tsx
apps/3001-shop/project.json
apps/3002-checkout/project.json
package.json
packages/nextjs-mf/src/plugins/ChildFederationPlugin.ts
packages/nextjs-mf/src/plugins/NextFederationPlugin.ts
packages/node/README.md
packages/node/package.json
packages/node/src/index.ts
packages/node/src/plugins/CommonJsChunkLoadingPlugin.ts
packages/node/src/plugins/NodeFederationPlugin.ts
packages/node/src/plugins/StreamingTargetPlugin.ts
packages/node/src/plugins/UniversalFederationPlugin.ts
packages/utilities/src/utils/common.ts
yarn.lock

added universal federation plugin, copied over updates from node repo

Update node pluign

---

package.json
packages/nextjs-mf/package.json
packages/nextjs-mf/tsconfig.lib.json
packages/nextjs-mf/tsconfig.spec.json

All changes listed below in commit messages list

Small fixes

---

.husky/commit-msg

chore: husky can't resolve npx command when nvm is used

---

packages/nextjs-mf/package.json
packages/nextjs-mf/src/internal.ts
packages/node/package.json
packages/node/src/plugins/NodeFederationPlugin.ts

improve offline remotes, include one retry call, deal with bad initialization of lazy remotes

fix: improve handling of offline remotes

---

packages/typescript/src/lib/Typescript.ts

perf: implement simple caching mechanism for fs lookup

---

apps/3000-home/components/SharedNav.tsx
apps/3000-home/next.config.js
apps/3000-home/pages/_app.tsx
package.json
packages/nextjs-mf/utils/build-utils.ts
packages/node/src/plugins/LoadFileChunkLoadingRuntimeModule.ts
packages/node/src/plugins/NodeFederationPlugin.ts
packages/node/src/plugins/loadScript.ts
packages/node/src/utils/flush-chunks.js
packages/node/src/utils/hot-reload.js
packages/utilities/src/utils/common.ts

enabled interop with webpack browser side script injection.

[node] __webpack_require__.l (loadScript) runtime module added

---

packages/typescript/src/lib/Typescript.ts

fix: get types on remote url with subdirectory

---

packages/nextjs-mf/src/loaders/patchDefaultSharedLoader.ts
packages/nextjs-mf/src/plugins/NextFederationPlugin.ts

apply loader less aggressively to codebase

fix: improve include defaults loader

---

packages/nextjs-mf/src/loaders/patchDefaultSharedLoader.ts

fix: Can't resolve .../include-defaults.js by relative require

---

packages/nextjs-mf/package.json

fix: update next peer dep to 12.3.0

---

packages/nextjs-mf/src/plugins/NextFederationPlugin.ts

fix: improve loader paths for including defaults

---

packages/nextjs-mf/src/loaders/fixImageLoader.ts
packages/node/src/plugins/NodeFederationPlugin.ts
packages/node/src/plugins/loadScript.ts

feat: support ssr remote entry images

---

.github/workflows/release.yml

* always build libs
Co-authored-by: Ran Shamay <ranshamay@microsoft.com>

always build libs (#381)

---

packages/typescript/src/plugins/FederatedTypesPlugin.ts

watch options to ignore - path normalization on windows 

---

CODE_OF_CONDUCT.md

Please, review and merge, if I didn't mess everything up :D

Added CODE_OF_CONDUCT

---

package.json
packages/typescript/README.md
packages/typescript/package.json
packages/typescript/src/lib/TypescriptCompiler.ts
packages/typescript/src/lib/normalizeOptions.ts
packages/typescript/src/plugins/FederatedTypesPlugin.ts
packages/typescript/src/types/index.ts
packages/utilities/package.json
yarn.lock

This PR adds the ability to support Vue library to generate remote types from Vue templates
closes #502

feat(typescript): support vue typescript compiler

---

packages/typescript/src/plugins/FederatedTypesPlugin.ts

fix(typescript): webpack bails when remote is unavailable

---

apps/3000-home/pages/home/test-broken-remotes.tsx
apps/3001-shop/next.config.js
apps/3001-shop/pages/_document.js
apps/3002-checkout/next.config.js

Fixes related to `nextjs-mf` pages loading
Document with issues: 
https://docs.google.com/spreadsheets/d/1RPJxmf22_5jnB7UmWRfKSKcw-bI6awMl5EpDiw0Ktqs/edit#gid=319639235

fix nextjs-mf page loading

---

packages/nextjs-mf/src/internal.ts

fix: getOutputPath to find if endsWith server

---

apps/3000-home/pages/home/test-remote-hook.tsx
apps/3002-checkout/next.config.js
yarn.lock

Fix the home_app reference in checkout and the remote hook call to default()

Delegates fix remotes

---

apps/3000-home/package.json
apps/3001-shop/package.json
apps/3002-checkout/package.json
package.json
yarn.lock

Causes NX to use a linked dependency of module-federation/node instead of semantic versions

fix: resolve NX build version issues

---

packages/typescript/src/plugins/FederatedTypesPlugin.ts
yarn.lock

Fix for issue #648 
I was not able to reproduce this issue but this seems like safer url building

Safely build url to download type files

---

packages/typescript/README.md

Fixes Typo in import

---

.github/workflows/pre-release.yml

- Test step inserted in the CI
- Extracted logic to retrieve effected projects

feat: edit ci

---

packages/native-federation-typescript/src/index.ts

fix: native-federation-typescript build

fix: ts build

---

packages/native-federation-tests/src/index.ts

External deps should be removed using the startsWith strategy

fix: tests regex

---

packages/nextjs-mf/README.md

fix(nextjs-mf): readme

---

gpt/filev2.js
gpt/filev2.test.js
gpt/response-template/code.js
gpt/response-template/template-factory.js
package-lock.json
package.json
packages/nextjs-mf/CHANGELOG.md
packages/nextjs-mf/package.json
packages/nextjs-mf/src/include-defaults.ts
packages/nextjs-mf/src/internal.ts
packages/nextjs-mf/src/loaders/patchDefaultSharedLoader.ts
packages/nextjs-mf/src/plugins/NextFederationPlugin/apply-server-plugins.ts
packages/nextjs-mf/src/plugins/NextFederationPlugin/next-fragments.ts
packages/nextjs-mf/src/plugins/container/InvertedContainerPlugin.ts
packages/nextjs-mf/src/plugins/container/RemoveEagerModulesFromRuntimePlugin.ts
packages/utilities/src/utils/common.ts

This update enhances the default share scope properties, prevents the removal of external eager modules, fixes production build issues, and updates the package release version.
- Update default share scope properties
- Set eager property for specific dependencies in DEFAULT_SHARE_SCOPE objects
- Remove JSON clone process and use a direct reference of DEFAULT_SHARE_SCOPE
- chore: update packscript
- No explanation provided
- fix: Prevent removal of external eager modules
- Remove unnecessary condition and improve code readability
- Refactor test patterns for better readability

fix: Improved Share Scope Properties and Fixed Production Build Issues

---

packages/nextjs-mf/src/plugins/container/InvertedContainerPlugin.ts
packages/nextjs-mf/src/plugins/container/InvertedContainerRuntimeModule.ts

This update focuses on enhancing the detection of entrypoint modules while excluding abnormal modules, as well as removing deprecated entryModule usage.
- refactor: remove use of deprecated entryModule
- Replaces usage of the deprecated entryModule with a more updated approach.
- Ensures compatibility with newer versions and reduces the risk of potential future issues.
- fix: improve detection of entrypoint modules
- Enhances the identification of "NormalModule" type entrypoint modules.
- Excludes abnormal modules from the search to optimize entrypoint detection accuracy.

fix:  Improved Entrypoint Module Detection and Refactoring

---

packages/native-federation-tests/src/configurations/hostPlugin.ts
packages/native-federation-typescript/src/configurations/hostPlugin.ts

closes: #949 
Removed .at(-1) in favour of plain old [length-1]

fix: removed .at(-1) in favour of [length-1]

---

package-lock.json
packages/nextjs-mf/src/plugins/NextFederationPlugin/apply-server-plugins.ts
packages/nextjs-mf/src/plugins/container/InvertedContainerRuntimeModule.ts

This update addresses the non-deterministic chunk ID handling issue which caused inconsistencies in the output. The fixes in this series of commits ensure a more reliable and consistent behavior.
* fix: address non-determinstic chunk id handling
* Updated the chunk ID generation process to be more reliable and deterministic
* Modified the code to handle cases where non-deterministic chunk IDs caused inconsistencies in the output

fix: Non-Deterministic Chunk ID Handling

---

apps/website/src/components/footer/footer.tsx

fix(footer): fixed background to be blurry

---

gpt/constants.js
packages/node/src/plugins/ChunkCorrelationPlugin.js
packages/node/src/plugins/StreamingTargetPlugin.ts
packages/node/src/plugins/UniversalFederationPlugin.ts

detect and auto patch incorrect configs when apply node federation plugin via universal federation plugin
improves #1105 
fixes #1094

fix: better automatic server build detection

---

apps/3000-home/remote-delegate.js
apps/3001-shop/remote-delegate.js
package-lock.json
packages/nextjs-mf/importDelegatedModule.ts
packages/nextjs-mf/src/plugins/container/RemoveEagerModulesFromRuntimePlugin.ts
packages/utilities/src/plugins/DelegateModulesPlugin.test.ts
packages/utilities/src/plugins/DelegateModulesPlugin.ts
packages/utilities/src/utils/importDelegatedModule.ts

I remove eager modules from remote, but in doing so also removes dependencies of delegate moduels, this preserves dependency tree of delegate module and removes all other eager references from eager:true

fix: prevent module graph connection conflict

---

packages/typescript/package.json

Enables support for moduleResolution: Bundler configured projects

fix(typescript): add types field to package.json exports

---

packages/nextjs-mf/utils/index.ts
packages/utilities/src/utils/common.ts
packages/utilities/src/utils/getRuntimeRemotes.test.ts
packages/utilities/src/utils/getRuntimeRemotes.ts
packages/utilities/src/utils/pure.ts

fix: improve import ordering

---

apps/3000-home/remote-delegate.js
apps/3001-shop/remote-delegate.js
apps/3002-checkout/remote-delegate.js
packages/nextjs-mf/CHANGELOG.md
packages/nextjs-mf/importDelegatedModule.ts
packages/nextjs-mf/package.json
packages/nextjs-mf/src/default-delegate.ts
packages/node/CHANGELOG.md
packages/node/package.json
packages/storybook-addon/CHANGELOG.md
packages/storybook-addon/package.json
packages/utilities/CHANGELOG.md
packages/utilities/package.json
packages/utilities/src/plugins/DelegateModulesPlugin.test.ts
packages/utilities/src/plugins/DelegateModulesPlugin.ts

Due to issue with delegate modules, graph references are being improperly copied. 
As a workaround, ive created a delegate module what it "pure"

fix: workaround to self ref module error in prod

---

packages/core/src/api/api.ts
packages/core/src/integrations/webpack/factory.ts
packages/core/src/lib/containers.ts

chore: core simplify

---

packages/nextjs-mf/README.md
packages/nextjs-mf/src/plugins/NextFederationPlugin/index.ts
packages/node/src/utils/flush-chunks.ts

fix: Next env variables,  readme, housekeeping

---

packages/enhanced/src/lib/container/AsyncBoundaryPlugin.ts
packages/nextjs-mf/src/internal.ts

fix: ensure chunk handler exists before calling it

---

.github/workflows/deploy-website.yml

Fixes this action error by specifying the website project as the build target project
https://github.com/module-federation/universe/actions/runs/6502272978/job/17661098179

fix: specify the netlify build project

---

packages/enhanced/src/lib/container/ModuleFederationPlugin.ts
packages/enhanced/src/schemas/container/ModuleFederationPlugin.check.ts
packages/enhanced/src/schemas/container/ModuleFederationPlugin.ts

fixing import paths for options validation

fix(enhanced): correct schema validation issues

---

packages/runtime/package.json

fix(runtime): fix type definition

---

.github/workflows/build-and-test.yml
packages/nextjs-mf/.eslintrc.json
packages/nextjs-mf/project.json
packages/nextjs-mf/src/loaders/fixImageLoader.ts
packages/nextjs-mf/src/plugins/CopyFederationPlugin.ts
packages/nextjs-mf/src/plugins/NextFederationPlugin/index.ts
packages/nextjs-mf/src/plugins/NextFederationPlugin/next-fragments.ts
packages/nextjs-mf/src/plugins/container/InvertedContainerPlugin.ts
packages/nextjs-mf/src/plugins/container/InvertedContainerRuntimeModule.ts
packages/nextjs-mf/src/plugins/container/ModuleFederationPlugin.ts
packages/nextjs-mf/tsconfig.json
packages/nextjs-mf/tsconfig.lib.json
packages/nextjs-mf/tsconfig.spec.json
packages/node/.eslintrc.json
packages/node/project.json
packages/node/src/plugins/AutomaticPublicPathPlugin.ts
packages/node/src/plugins/CommonJsChunkLoadingPlugin.ts
packages/node/src/plugins/DynamicFilesystemChunkLoadingRuntimeModule.ts
packages/node/src/plugins/NodeFederationPlugin.ts
packages/node/src/plugins/RemotePublicPathRuntimeModule.ts
packages/node/src/plugins/StreamingTargetPlugin.ts
packages/node/src/plugins/UniversalFederationPlugin.ts
packages/node/src/plugins/webpackChunkUtilities.ts
packages/sdk/package.json
packages/sdk/project.json
packages/utilities/src/utils/common.ts

ban imports of webpack without normalize wrapper. 
switch over upper packages to normalized import

refactor(nextjs-mf): Normalized webpack path import

---

.npmrc
package-lock.json
package.json

inquirer@9 only allow es module

fix: downgrade inquirer version

---

CONTRIBUTING.md

feat: add contribute doc

---

README.md
tsconfig.base.json

* docs: Optimize readme content
#1737

docs: Optimize readme content

---

README.md

* docs: fix the contribution guide link error
#1738

docs: fix the contribution guide link error

---

README.md

* Add credits to ensure compliance

docs: add credits

---

README.md

style: formatting readme

---

apps/runtime-demo/host/src/runtimePlugin.ts
packages/runtime/README.md
packages/runtime/__tests__/hooks.spec.ts
packages/runtime/src/core.ts
packages/runtime/src/plugins/snapshot/index.ts

refactor(runtime): rename hooks

---

.husky/commit-msg
.npmrc
nxrelease.config.js
package-lock.json
package.json

* fix release workflow
* downgrade inquirer version
* add npm registry

ci: fix release workflow

---

packages/nextjs-mf/src/plugins/container/runtimePlugin.ts
packages/runtime/src/core.ts
packages/runtime/src/plugins/generate-preload-assets.ts
packages/runtime/src/utils/share.ts

Implementation of loadShare hook
Adding hook that allows manual brokering of shared modules. 
N/A

feat(runtime): resolve share hook added

---

.husky/pre-commit
commitlint.config.js

* chore(workflow): modify commitlint scope rules
none

chore(workflow): modify commitlint scope rules

---

apps/3000-home/cypress.config.ts
apps/3000-home/cypress/e2e/app.cy.ts
apps/3000-home/next.config.js
apps/3000-home/pages/_app.tsx
apps/3000-home/pages/index.tsx
apps/3001-shop/cypress.config.ts
apps/3001-shop/cypress/e2e/app.cy.ts
apps/3001-shop/next.config.js
apps/3001-shop/pages/_app.tsx
apps/3001-shop/pages/shop/index.tsx
apps/3002-checkout/components/CheckoutTitle.tsx
apps/3002-checkout/cypress.config.ts
apps/3002-checkout/cypress/e2e/app.cy.ts
apps/3002-checkout/next.config.js
apps/3002-checkout/pages/_app.tsx
apps/3002-checkout/pages/checkout/index.tsx
apps/node-host/tsconfig.json
apps/node-host/webpack.config.js

Update next app configs with canary branch

chore: update next apps

---

packages/enhanced/src/lib/container/ContainerPlugin.ts

Add additional EntryDependency with no set runtime chunk 
This pull request addresses an issue discovered during container plugin use, specifically concerning the runtime management. During a chat with a colleague, we arrive at an understanding that there is a need for us to generate an entry that does not include runtime.
In a scenario where an application APP1 imports a component from a shell and the Shell imports a page from APP1, APP1 downloads `remoteEntry.js`, which in turn will replace the `chunkLoadingGlobal`. This replaces the chunk loading mechanism in the host, disabling the ability to push chunks into its runtime.
With the enhancements of this pull request, a host can add its "remote name and data" to `remotes` or `moduleCache`, thereby circumventing an issue where …

feat(enhanced): single runtime chunk support in container

---

packages/runtime/rollup.config.js
packages/runtime/src/global.ts

Prevent __VERSION__ from throwing undefined error during tests or if package is transpiled via tspaths and not using the rollup built output

fix: use string placeholder to prevent undefined variable

---

.github/workflows/release.yml
.prettierignore
apps/node-host-e2e/package.json
apps/node-host/package.json
apps/node-local-remote/package.json
apps/node-remote/package.json
packages/sdk/package.json

* chore(workflow): Optimize affected pkg after release

chore(workflow): optimize affected pkg after release 

---

.prettierignore

chore(workflow): ignore dist lint

---

apps/node-remote/package.json

* chore(workflow): ignore node-remote applications to avoid publishing it

chore(workflow): ignore node-remote applications to avoid publishing it

---

.changeset/chilly-colts-eat.md
.eslintignore
.github/workflows/release.yml
apps/node-host/project.json
packages/core/package.json
packages/enhanced/package.json
packages/native-federation-tests/package.json
packages/native-federation-typescript/package.json
packages/nextjs-mf/package.json
packages/node/package.json
packages/runtime/package.json
packages/sdk/package.json
packages/storybook-addon/package.json
packages/typescript/package.json
packages/utilities/package.json
packages/webpack-bundler-runtime/package.json
tsconfig.tmp.json

* chore(workflow): fix release pkg logic

chore(workflow): fix release pkg logic

---

.changeset/wet-dancers-raise.md
commitlint.config.js
packages/runtime/__tests__/load-remote.spec.ts
packages/runtime/__tests__/mock/handlers.ts
packages/runtime/__tests__/mock/mock-script.ts
packages/runtime/src/utils/tool.ts
packages/sdk/src/generateSnapshotFromManifest.ts
packages/sdk/src/utils.ts

feat(runtime): support entry with query

---

.changeset/stale-horses-bathe.md
.github/workflows/build-and-test.yml
packages/sdk/src/index.ts

export sdk simpleJoinRemoteEntry function

chore: export sdk simpleJoinRemoteEntry function

---

.github/release.yml

chore: add release note

---

.changeset/honest-peas-dress.md
packages/enhanced/CHANGELOG.md
packages/enhanced/package.json
packages/nextjs-mf/CHANGELOG.md
packages/nextjs-mf/package.json
packages/node/CHANGELOG.md
packages/node/package.json
packages/runtime/CHANGELOG.md
packages/runtime/package.json
packages/sdk/CHANGELOG.md
packages/sdk/package.json
packages/webpack-bundler-runtime/CHANGELOG.md
packages/webpack-bundler-runtime/package.json

##What's Changed
* fix: rename usePlugins to prevent swc react-refresh from throwing errors when replacing variables by @2heal1 in https://github.com/module-federation/universe/pull/1880
* chore: add release note by @zhoushaw in https://github.com/module-federation/universe/pull/1864
Full Changelog: https://github.com/module-federation/universe/compare/v0.0.5...v0.0.6

Release v0.0.6

---

renovate.json

* chore: modify renovate schedule
none

chore: modify renovate schedule

---

packages/enhanced/src/wrapper/FederationRuntimePlugin.ts

federationRuntimePlugin options should be partial

fix: federationRuntimePlugin options should be partial

---

packages/enhanced/src/wrapper/FederationRuntimePlugin.ts

feat: add plugin instance attr

---

packages/enhanced/package.json
packages/enhanced/src/lib/container/runtime/FederationRuntimePlugin.ts
packages/enhanced/src/lib/container/runtime/utils.ts
packages/enhanced/src/schemas/container/ModuleFederationPlugin.ts
packages/enhanced/src/types/runtime.ts
pnpm-lock.yaml

use runtime tools, and it will auto set alias with passed implementation configuration

chore: use runtime tools

---

packages/runtime/__tests__/resources/version-strategy-app2/federation-remote-entry.js
packages/runtime/__tests__/shares.spec.ts
packages/runtime/src/utils/share.ts

feat: add shared strategy test

---

packages/runtime/src/core.ts

remove duplicate register warning

chore: remove duplicate register warning

---

packages/runtime/src/core.ts
packages/webpack-bundler-runtime/src/initContainerEntry.ts

chore: remove compat code

---

package.json
pnpm-lock.yaml

chore: solve merge conflict

---

apps/docs-ui/webpack.config.js
apps/docs/configs/docs-en.local.yml
apps/docs/configs/docs-en.yml
apps/docs/configs/docs-es.local.yml
apps/docs/configs/docs-es.yml
apps/docs/configs/docs-zh.local.yml
apps/docs/configs/docs-zh.yml

chore: fix doc paths

---

apps/node-host/webpack.config.js
apps/node-local-remote/project.json
apps/node-remote/project.json
apps/reactRemoteUI/project.json
apps/reactStorybook/project.json
package.json

remove deprecations from NX in apps

chore: remove isolated config

---

.github/workflows/build-and-test.yml

Improves reliability of next.js e2e by running each e2e test one at a time and restarting next instances between tests

ci: improve e2e stability of next

---

.github/workflows/issue-close-require.yml
.github/workflows/issue-labeled.yml

workflow: add issue labeled

---

.changeset/silent-lions-impress.md
packages/enhanced/CHANGELOG.md
packages/enhanced/package.json
packages/nextjs-mf/CHANGELOG.md
packages/nextjs-mf/package.json
packages/node/CHANGELOG.md
packages/node/package.json
packages/runtime-tools/CHANGELOG.md
packages/runtime-tools/package.json
packages/runtime/CHANGELOG.md
packages/runtime/package.json
packages/sdk/CHANGELOG.md
packages/sdk/package.json
packages/webpack-bundler-runtime/CHANGELOG.md
packages/webpack-bundler-runtime/package.json

* fix(enhanced): use upath to against more edge cases between different OS by @2heal1 in https://github.com/module-federation/universe/pull/2070
null
**Full Changelog**: https://github.com/module-federation/universe/compare/v0.0.11...v0.0.12

Release v0.0.12

---

.changeset/forty-dolls-dance.md
packages/enhanced/CHANGELOG.md
packages/enhanced/package.json
packages/nextjs-mf/CHANGELOG.md
packages/nextjs-mf/package.json
packages/node/CHANGELOG.md
packages/node/package.json
packages/runtime-tools/CHANGELOG.md
packages/runtime-tools/package.json
packages/runtime/CHANGELOG.md
packages/runtime/package.json
packages/sdk/CHANGELOG.md
packages/sdk/package.json
packages/webpack-bundler-runtime/CHANGELOG.md
packages/webpack-bundler-runtime/package.json

* fix(runtime): use link to preload js assets by @2heal1 in https://github.com/module-federation/universe/pull/2071
null
**Full Changelog**: https://github.com/module-federation/universe/compare/v0.0.12...v0.0.13

Release v0.0.13

---

apps/runtime-demo/3005-runtime-host/webpack.config.js
apps/runtime-demo/3006-runtime-remote/webpack.config.js
packages/enhanced/src/schemas/container/ContainerPlugin.check.ts
packages/enhanced/src/schemas/container/ContainerReferencePlugin.check.ts
packages/enhanced/src/schemas/container/ModuleFederationPlugin.check.ts

chore: remove useless code

---

apps/3000-home/package.json
apps/3001-shop/cypress/e2e/app.cy.ts
apps/3001-shop/package.json
apps/3002-checkout/package.json
pnpm-lock.yaml

update next packages for prod build, improve e2e reliabilty
N/A

chore: update next packages and improve e2e

---

apps/modernjs/project.json

test: fix e2e for modernjs

---

.github/workflows/build-and-test.yml
apps/node-host-e2e/project.json

chore: resolve node e2e errors

---

apps/modernjs/package.json
pnpm-lock.yaml

chore: scope modernjs app correctly

---

.changeset/tender-steaks-know.md
packages/node/package.json
pnpm-lock.yaml

install encoding peer dep
https://github.com/module-federation/module-federation-examples/issues/3636

fix(node): install encoding peer dep

---

apps/3000-home/package.json
apps/3001-shop/package.json
apps/3002-checkout/package.json
package.json
packages/nextjs-mf/src/plugins/NextFederationPlugin/next-fragments.ts
pnpm-lock.yaml

Fix ruleSet errors 
https://github.com/module-federation/universe/pull/2149

fix(nextjs-mf): fix next 14 loader rules

---

.changeset/itchy-ravens-give.md
.changeset/lazy-tables-prove.md
.changeset/rude-melons-press.md
.changeset/warm-berries-serve.md
apps/modernjs/CHANGELOG.md
apps/modernjs/package.json
packages/enhanced-rspack/CHANGELOG.md
packages/enhanced-rspack/package.json
packages/enhanced/CHANGELOG.md
packages/enhanced/package.json
packages/managers/CHANGELOG.md
packages/managers/package.json
packages/manifest/CHANGELOG.md
packages/manifest/package.json
packages/nextjs-mf/CHANGELOG.md
packages/nextjs-mf/package.json
packages/node/CHANGELOG.md
packages/node/package.json
packages/runtime-tools/CHANGELOG.md
packages/runtime-tools/package.json
packages/runtime/CHANGELOG.md
packages/runtime/package.json
packages/sdk/CHANGELOG.md
packages/sdk/package.json
packages/webpack-bundler-runtime/CHANGELOG.md
packages/webpack-bundler-runtime/package.json

* feat: generate manifest and consume it by @2heal1 in https://github.com/module-federation/universe/pull/2108
* fix(nextjs-mf): fix next 14 loader rules by @ScriptedAlchemy in https://github.com/module-federation/universe/pull/2149
* fix(runtime): The preload link is inserted without specific purpose by @zhoushaw in https://github.com/module-federation/universe/pull/2152
* fix(runtime): preserve error.stack instead of throwing new error by @2heal1 in https://github.com/module-federation/universe/pull/2153
* Release v0.0.14 by @zhoushaw in https://github.com/module-federation/universe/pull/2148
* release docs by @ScriptedAlchemy in https://github.com/module-federation/universe/pull/2150
* Nextjs plugin Release v8.2.0 by @zhoushaw in https://github.com/module-federation/universe/pull/2151 …

Release v0.0.15

---

.changeset/shiny-feet-buy.md
packages/manifest/src/StatsManager.ts

fix(manifest): apply stats options

---

.changeset/shiny-feet-buy.md
apps/modernjs/CHANGELOG.md
apps/modernjs/package.json
packages/enhanced-rspack/CHANGELOG.md
packages/enhanced-rspack/package.json
packages/enhanced/CHANGELOG.md
packages/enhanced/package.json
packages/managers/CHANGELOG.md
packages/managers/package.json
packages/manifest/CHANGELOG.md
packages/manifest/package.json
packages/nextjs-mf/CHANGELOG.md
packages/nextjs-mf/package.json
packages/node/CHANGELOG.md
packages/node/package.json
packages/runtime-tools/CHANGELOG.md
packages/runtime-tools/package.json
packages/runtime/CHANGELOG.md
packages/runtime/package.json
packages/sdk/CHANGELOG.md
packages/sdk/package.json
packages/webpack-bundler-runtime/CHANGELOG.md
packages/webpack-bundler-runtime/package.json

* fix(nextjs-mf): fix static method function proxy assignment by @ScriptedAlchemy in https://github.com/module-federation/universe/pull/2156
* fix(manifest): apply stats options by @2heal1 in https://github.com/module-federation/universe/pull/2175
* Release v0.0.15 by @zhoushaw in https://github.com/module-federation/universe/pull/2170
* Release v8.2.2 by @zhoushaw in https://github.com/module-federation/universe/pull/2173
* chore(deps): update dependency webpack to v5.76.0 [security] by @renovate in https://github.com/module-federation/universe/pull/2169
**Full Changelog**: https://github.com/module-federation/universe/compare/v0.0.15...v0.0.16

Release v0.0.16

---

.changeset/swift-boats-cough.md
.github/workflows/build-and-test.yml
apps/modernjs/CHANGELOG.md
apps/modernjs/package.json
packages/enhanced-rspack/CHANGELOG.md
packages/enhanced-rspack/package.json
packages/enhanced/CHANGELOG.md
packages/enhanced/package.json
packages/managers/CHANGELOG.md
packages/managers/package.json
packages/manifest/CHANGELOG.md
packages/manifest/package.json
packages/nextjs-mf/CHANGELOG.md
packages/nextjs-mf/package.json
packages/node/CHANGELOG.md
packages/node/package.json
packages/runtime-tools/CHANGELOG.md
packages/runtime-tools/package.json
packages/runtime/CHANGELOG.md
packages/runtime/package.json
packages/sdk/CHANGELOG.md
packages/sdk/package.json
packages/webpack-bundler-runtime/CHANGELOG.md
packages/webpack-bundler-runtime/package.json

* feat: add registerRemotes api by @2heal1 in https://github.com/module-federation/universe/pull/2171
* fix(website): fixed build and deployment for website and docs by @lexasq in https://github.com/module-federation/universe/pull/2172
* Release v0.0.16 by @zhoushaw in https://github.com/module-federation/universe/pull/2176
**Full Changelog**: https://github.com/module-federation/universe/compare/v0.0.16...v0.0.17

Release v0.0.17

---

packages/node/README.md

Fixes a typo in Readme for overriding fetch behaviour, and slightly tidies up the description. 
n/a

Minor documentation tidy up for `@module-federation/node` 

---

package.json
pnpm-lock.yaml

chore: remove unless deps

---

.changeset/rich-onions-flow.md

chore(enhanced): bump for release

---

apps/docs/src/en/modules/ROOT/pages/core-features/dynamic-remotes.adoc

This PR removes an unnecessary closing bracket from the code snippet.
None

chore(docs): remove unnecessary closing bracket

---

packages/nextjs-mf/src/plugins/NextFederationPlugin/index.ts

feat: wire skipSharingNextInternals

---

apps/docs/src/en/modules/ROOT/pages/core-features/dynamic-remotes.adoc

In case of initialization error, promise will never end

fix(docs): add reject in promise-based dynamic remote

---

apps/website-new/docs/en/configure/name.mdx
apps/website-new/docs/en/configure/shared.mdx
apps/website-new/docs/zh/configure/name.mdx
apps/website-new/docs/zh/configure/shared.mdx
apps/website-new/src/components/ShowcaseList/index.module.scss
apps/website-new/src/components/ShowcaseList/index.tsx

* update name config
* remove sharedStrategy
* update showcase

docs: optimize doc

---

.changeset/happy-mugs-fail.md
apps/manifest-demo/3010-rspack-provider/package.json
apps/manifest-demo/3010-rspack-provider/rspack.config.js
apps/manifest-demo/3011-rspack-manifest-provider/package.json
apps/manifest-demo/3011-rspack-manifest-provider/rspack.config.js
apps/manifest-demo/3012-rspack-js-entry-provider/package.json
apps/manifest-demo/3012-rspack-js-entry-provider/rspack.config.js
apps/react-ts-remote/package.json
apps/react-ts-remote/rspack.config.js
packages/enhanced/package.json
packages/enhanced/src/rspack.ts
packages/enhanced/src/runtime.ts
packages/enhanced/src/webpack.ts
pnpm-lock.yaml

convergence of all package entries

chore: convergence of all package entries

---

packages/enhanced/src/lib/container/runtime/FederationRuntimePlugin.ts
packages/runtime/README.md
packages/runtime/src/core.ts
packages/runtime/src/index.ts

expose registerPlugins api
Avoid excessively calling init when lazy registering runtime plugins

feat(enhanced): register plugins exposed runtime api

---

README.md

doc: optimize readme

---

README.md

doc: optimize README.md

---

apps/website-new/docs/en/guide/start/quick-start.mdx
apps/website-new/docs/zh/guide/start/quick-start.mdx

* doc: optimize quick start type declaration

doc: optimize quick start type declaration

---

README.md
packages/utilities/README.md

* docs: lists past underlying packages
none

docs: lists past underlying packages

---

apps/website-new/docs/en/guide/basic/type-prompt.mdx

docs: update type-prompt.mdx

---

.changeset/quiet-ways-shake.md
packages/enhanced/src/lib/sharing/ConsumeSharedRuntimeModule.ts

fix: chunkId may equal number 0

fix: chunkId may equal number 0

---

.changeset/gentle-kings-remember.md
packages/enhanced/package.json
packages/runtime-tools/package.json
packages/runtime/package.json
packages/sdk/package.json

fix: fixed type declaration in pkg

fix: fixed type declaration in pkg

---

apps/website-new/docs/en/guide/start/quick-start.mdx
apps/website-new/docs/zh/guide/start/quick-start.mdx

* docs: optimize quick start content

docs: optimize quick start content

---

package.json
packages/chrome-devtools/project.json
packages/core/project.json
packages/dts-plugin/project.json
packages/enhanced/project.json
packages/managers/project.json
packages/manifest/project.json
packages/native-federation-tests/project.json
packages/native-federation-typescript/project.json
packages/nextjs-mf/project.json
packages/node/project.json
packages/rspack/project.json
packages/runtime-tools/project.json
packages/runtime/project.json
packages/sdk/project.json
packages/storybook-addon/project.json
packages/third-party-dts-extractor/project.json
packages/typescript/project.json
packages/utilities/project.json
packages/webpack-bundler-runtime/project.json

* chore: modify build:pkg command

chore: modify build:pkg command

---

.changeset/twelve-peas-melt.md
packages/manifest/src/ManifestManager.ts
packages/manifest/src/StatsPlugin.ts
packages/sdk/src/types/plugins/ModuleFederationPlugin.ts

feat: support config manifest

---

.changeset/config.json
.changeset/heavy-guests-refuse.md
.github/workflows/release.yml
packages/runtime/__tests__/shares.spec.ts

chore: fix release tag

---

.changeset/tame-mirrors-greet.md
packages/runtime/src/utils/share.ts

support config string shareScope

fix: support config string shareScope

---

.changeset/mean-months-sparkle.md
packages/native-federation-tests/src/lib/archiveHandler.ts
packages/native-federation-typescript/src/lib/archiveHandler.ts

fix: download retrieves count per file

---

.changeset/sweet-shirts-eat.md

chore: add miss changeset
https://github.com/module-federation/universe/pull/2341

chore: add miss changeset

---

.changeset/purple-apples-battle.md
.changeset/strong-grapes-tap.md
.github/workflows/build-and-test.yml
apps/3000-home/cypress/e2e/app.cy.ts
apps/3000-home/next.config.js
apps/3000-home/package.json
apps/3001-shop/cypress/e2e/app.cy.ts
apps/3001-shop/next.config.js
apps/3001-shop/package.json
apps/3001-shop/pages/shop/index.tsx
apps/3002-checkout/cypress/e2e/app.cy.ts
apps/3002-checkout/next.config.js
apps/3002-checkout/package.json
apps/3002-checkout/pages/checkout/index.tsx
nx.json
package.json
packages/enhanced/src/lib/container/ContainerPlugin.ts
packages/enhanced/src/lib/container/HoistContainerReferencesPlugin.ts
packages/enhanced/src/wrapper/HoistContainerReferencesPlugin.ts
packages/nextjs-mf/src/plugins/NextFederationPlugin/apply-client-plugins.ts
packages/nextjs-mf/src/plugins/NextFederationPlugin/apply-server-plugins.ts
packages/nextjs-mf/src/plugins/NextFederationPlugin/index.ts
packages/rspack/src/ModuleFederationPlugin.ts

ensure that _partial secondary runtime chunk that is added when runtimeChunk: single is also patched from chunk split
dont break secondary container when single runtime chunk is used. This ensures a single runtime chunk container chunk can still be used in the future

fix: patch chunk split of "_partial" container entry 

---

.github/workflows/build-and-test.yml
apps/3000-home/cypress/e2e/app.cy.ts
apps/3001-shop/cypress/e2e/app.cy.ts
apps/3002-checkout/cypress/e2e/app.cy.ts

chore: fix e2e ci temp issue

---

.changeset/rich-peaches-tan.md
apps/website-new/docs/en/plugin/plugins/index.mdx

Fix doc imports for rspack and webpack enhanced

chore: fix doc imports for node

---

apps/website-new/docs/en/guide/basic/type-prompt.mdx
apps/website-new/docs/en/guide/framework/nextjs.mdx

update documentation on next, pull from docs/framework branch

docs: update next docs

---

README.md

* docs: optimize readme module federation 2.0

docs: optimize readme module federation 2.0

---

apps/modernjs/modern.config.ts

update app include regex for /core/ repo name

chore: update regex for modern app

---

apps/website-new/docs/en/practice/frameworks/next/express.mdx

fix: dead links

---

apps/website-new/docs/en/guide/start/npm-packages.mdx
apps/website-new/docs/zh/guide/start/npm-packages.mdx

docs: add new npm pkg

---

.changeset/good-toes-beg.md

chore: update changeset

---

.changeset/strange-points-play.md
packages/enhanced/package.json
packages/enhanced/src/webpack.ts

chore(enhanced): fix esm exports 

---

.github/workflows/build-and-test.yml
.github/workflows/release.yml

* chore: fix build and test ci error

chore: fix build and test ci error

---

apps/website-new/docs/en/guide/start/npm-packages.mdx
apps/website-new/docs/zh/guide/start/npm-packages.mdx

Better description for native-federation-typescript.
People who are leveraging community plugins for vite, cannot easily switch to the enhanced package so we should point that this is still the plugin for them.
@zhoushaw I need your help for the translation

docs:  native ts description

---

.changeset/wild-queens-dress.md
packages/chrome-devtools/README.md
packages/chrome-devtools/package.json

fix: fix publish private error

---

apps/website-new/docs/en/guide/basic/runtime.mdx

docs: Update runtime.mdx

---

packages/enhanced/package.json

Causes tests to fail in enhanced test cases

fix(enhanced): remove package type

---

apps/website-new/docs/en/guide/basic/chrome-devtool.mdx
apps/website-new/docs/zh/guide/basic/chrome-devtool.mdx

docs: remove unless vmok name

---

apps/website-new/netlify.toml

* docs: resolve google module federation get start link break

docs: resolve google module federation get start link break

---

apps/website-new/docs/en/blog/announcement.mdx
apps/website-new/docs/zh/blog/announcement.mdx

docs: updating announcement

---

apps/website-new/docs/en/practice/frameworks/next/presets.mdx

docs: update presets.mdx

---

apps/website-new/docs/zh/configure/index.mdx

docs: delete dumplicate property

---

.changeset/fair-mirrors-design.md
packages/typescript/package.json
pnpm-lock.yaml

add missing lodash.get dep
https://github.com/module-federation/core/issues/2426

fix(typescript): add missing dep

---

.changeset/fair-trains-search.md
packages/node/src/runtimePlugin.ts

correct order of chunk evaluation

fix(node): correct chunk evaluation order

---

.changeset/twenty-birds-shop.md

chore: release runtime

---

apps/website-new/docs/en/guide/basic/rspack.mdx
apps/website-new/docs/zh/guide/basic/rspack.mdx

docs: fix rspack config demo

---

apps/node-host/webpack.config.js

Fix config issue when using public path and federation runtime plugin

chore: fix node public path sample

---

.changeset/brave-meals-hug.md
packages/webpack-bundler-runtime/src/installInitialConsumes.ts

add more details tip for loadShareSync

chore(webpack-bundler-runtime): add more details tip for loadShareSync

---

.changeset/eleven-turtles-glow.md
.changeset/wise-trains-live.md
packages/runtime/src/core.ts
packages/runtime/src/plugins/generate-preload-assets.ts
packages/runtime/src/plugins/snapshot/index.ts
packages/runtime/src/remote/index.ts
packages/runtime/src/shared/index.ts
packages/runtime/src/type/plugin.ts
packages/runtime/src/utils/plugin.ts

* extract shared relative logic to sharedHandler
* extract remio relative logic to sharedHandler

chore: optimize runtime structure

---

.changeset/forty-olives-hammer.md
packages/runtime/src/core.ts
packages/runtime/src/shared/index.ts
packages/runtime/src/utils/share.ts

should use userOptions.shared to apply hooks
#2382

fix: should use userOptions.shared to apply hooks

---

apps/esbuild/mfe1/federation.config.js
apps/esbuild/mfe1/main.ts
apps/esbuild/shell/app.tsx
apps/esbuild/shell/main.ts
packages/esbuild/src/adapters/lib/plugin.js
packages/esbuild/src/lib/core/createContainerTemplate.js
packages/esbuild/src/lib/core/get-externals.js
pnpm-lock.yaml

runtime plugin to implement import maps

feat(esbuild): import maps runtime plugin

---

.changeset/long-spies-march.md
apps/modernjs-ssr/dynamic-nested-remote/src/components/Content.tsx
apps/modernjs-ssr/nested-remote/src/components/Content.tsx
apps/modernjs-ssr/nested-remote/src/modern-app-env.d.ts
apps/modernjs/modern.config.ts
packages/dts-plugin/src/core/lib/DTSManager.ts
packages/dts-plugin/src/core/lib/DtsWorker.ts
packages/dts-plugin/src/core/lib/utils.ts
packages/dts-plugin/src/dev-worker/DevWorker.ts
packages/enhanced/src/lib/container/AsyncBoundaryPlugin.ts
packages/enhanced/src/schemas/container/ModuleFederationPlugin.ts
packages/manifest/src/ManifestManager.ts
packages/manifest/src/StatsManager.ts
packages/modernjs/project.json
packages/modernjs/src/cli/index.ts
packages/modernjs/src/cli/manifest.ts
packages/modernjs/src/cli/utils.ts
packages/modernjs/src/runtime/MFReactComponent.tsx
packages/modernjs/src/runtime/index.ts
packages/modernjs/src/types/index.ts
packages/rspack/src/ModuleFederationPlugin.ts
packages/runtime/src/index.ts
packages/runtime/src/plugins/snapshot/SnapshotHandler.ts
packages/runtime/src/plugins/snapshot/index.ts
packages/runtime/src/remote/index.ts
packages/sdk/src/generateSnapshotFromManifest.ts
packages/sdk/src/types/plugins/ModuleFederationPlugin.ts

feat: prevent css flickering

---

packages/modernjs/package.json
packages/modernjs/src/cli/index.ts
packages/modernjs/src/cli/mfRuntimePlugins/inject-node-fetch.ts
packages/modernjs/src/cli/utils.ts
packages/node/src/index.ts
packages/node/src/recordDynamicRemoteEntryHashPlugin.ts
packages/node/src/utils/hot-reload.ts
packages/runtime/src/remote/index.ts
packages/runtime/src/utils/load.ts
pnpm-lock.yaml

feat: inject node fetch

---

apps/website-new/docs/zh/practice/frameworks/react/index.mdx

docs: format rsbuild zh chapter

---

apps/esbuild/build/build-common.js
apps/esbuild/package.json
apps/esbuild/shell/main.ts
apps/esbuild/tsconfig.json
packages/esbuild/src/adapters/lib/containerPlugin.ts
packages/esbuild/src/adapters/lib/containerReference.ts

Use async init so that remotes init hooks are called before how proceedes

fix(esbuild): async init

---

apps/website-new/docs/en/guide/start/quick-start.mdx
apps/website-new/docs/zh/guide/start/quick-start.mdx

update href in quick-start.mdx files
https://module-federation.io/guide/basic/configure.html

docs: update href in quick-start.mdx files

---

.changeset/angry-items-cover.md
packages/manifest/src/ModuleHandler.ts

add requiredVersion to manifest.shared

fix: add requiredVersion to manifest.shared

---

.changeset/eleven-seals-deny.md
.changeset/seven-pans-argue.md
packages/manifest/src/StatsManager.ts
packages/runtime/src/plugins/snapshot/index.ts
packages/runtime/src/utils/load.ts
packages/sdk/src/types/stats.ts

add protocol in node automaticly

fix: add protocol in node automaticly

---

.changeset/quiet-parrots-battle.md
packages/runtime/src/utils/preload.ts
packages/sdk/src/dom.ts

do not delete link tag if no preload

fix: do not delete link tag if no preload

---

.changeset/eight-wolves-beg.md
packages/enhanced/package.json

Add the repository property to the enhanced package

feat(enhanced): add repository property to the enhanced package

---

apps/3000-home/cypress/e2e/app.cy.ts
apps/3001-shop/cypress/e2e/app.cy.ts
apps/3002-checkout/cypress/e2e/app.cy.ts

chore: disable next page warmer

---

.changeset/lazy-bees-act.md
packages/enhanced/package.json

Add the license property to the package.json file of module-federation/enhanced

chore(enhanced): add license property to package.json

---

.changeset/five-chefs-smoke.md
packages/runtime/src/module/index.ts

Do not add debugger if object cannot be extended
https://github.com/module-federation/core/issues/2590

fix(runtime): do not apply symbol if object not extensible

---

.changeset/little-pugs-lay.md
packages/chrome-devtools/src/utils/chrome/fast-refresh.ts

fix(chrome-devtools): fix sharedInfo conflict with userOptions.sharedInfo cause hmr fail

---

.changeset/three-adults-join.md
packages/sdk/src/utils.ts

use variable instead of constant

fix(sdk): use variable instead of constant

---

apps/website-new/docs/zh/guide/basic/runtime.mdx

docs: fix error link

---

.changeset/spotty-laws-sparkle.md
.changeset/weak-dolls-hug.md
packages/dts-plugin/src/plugins/DevPlugin.ts
packages/enhanced/package.json
pnpm-lock.yaml

* use userOptions.typesFolder first
* add peer deps required by dts plugin

fix: use userOptions.typesFolder first

---

.changeset/green-pants-sip.md
packages/dts-plugin/src/core/lib/DtsWorker.ts
packages/dts-plugin/src/core/lib/utils.ts

ensure kill fork child process when the task is finished

fix(dts-plugin): ensure kill fork child process when the task is finished

---

.changeset/lemon-pandas-drop.md
apps/website-new/docs/en/practice/bridge/index.mdx
apps/website-new/docs/en/practice/bridge/react-bridge.mdx
apps/website-new/docs/zh/practice/bridge/index.mdx
apps/website-new/docs/zh/practice/bridge/react-bridge.mdx
apps/website-new/docs/zh/practice/bridge/vue-bridge.mdx

* feat(bridge): Supports exporting and loading of application-level modules (with routing), currently supports react and vue3

feat(bridge): Supports exporting and loading of application-level modules (with routing), currently supports react and vue3

---

apps/website-new/docs/en/practice/bridge/react-bridge.mdx
apps/website-new/docs/zh/practice/bridge/react-bridge.mdx

* docs: update framework version

docs: update framework version

---

apps/website-new/docs/zh/practice/bridge/index.mdx

fix(docs): zh/practice/bridge/index link error

---

apps/website-new/docs/en/practice/bridge/index.mdx

fix english bridge overview title

fix(docs): english bridge overview title

---

apps/3000-home/next.config.js
apps/3000-home/package.json
apps/3000-home/pages/_app.tsx
apps/3000-home/pages/index.tsx
apps/3001-shop/next.config.js
apps/3001-shop/package.json
apps/3001-shop/pages/_app.tsx
apps/3002-checkout/next.config.js
apps/3002-checkout/package.json
apps/3002-checkout/pages/_app.tsx
apps/manifest-demo/3011-rspack-manifest-provider/package.json
apps/manifest-demo/3012-rspack-js-entry-provider/package.json
package.json
pnpm-lock.yaml

fix nextjs hydration issues caused by antd

chore: fix next hydration issues on antd

---

apps/router-demo/router-remote1-2001/src/bootstrap.tsx
apps/router-demo/router-remote3-2003/src/bootstrap.ts
apps/router-demo/router-remote3-2003/src/index.ts

chore: fix bridge e2e test

---

.github/workflows/build-and-test.yml

chore: disable next e2e prod

---

apps/router-demo/router-remote1-2001/rsbuild.config.ts
packages/bridge/bridge-react/src/create.tsx
packages/bridge/bridge-react/src/remote/index.tsx

* fix(react-bridge): optimize bridge router pathname

fix(react-bridge): optimize bridge router pathname

---

.changeset/afraid-chefs-yell.md
packages/dts-plugin/src/core/lib/DTSManager.advance.spec.ts
packages/dts-plugin/src/core/lib/DTSManager.ts
packages/dts-plugin/src/core/lib/typeScriptCompiler.ts
packages/dts-plugin/vite.config.ts

fix(dts-plugin): ensure dts file path if it has deep path

fix(dts-plugin): ensure dts file path if it has deep path

---

.changeset/config.json

chore: fix modernjs plugin version

---

.changeset/orange-carrots-fry.md
packages/dts-plugin/src/core/lib/typeScriptCompiler.ts

remove useless log
- [x ] All new and existing tests passed.

chore: remove useless log

---

.changeset/dull-cats-laugh.md

chore: add changeset

---

.changeset/dull-seals-suffer.md
packages/chrome-devtools/src/utils/sdk/graph.ts

fix(chrome-devtools): fix dependency graph lose node

---

apps/website-new/docs/en/guide/basic/rspack.mdx
apps/website-new/docs/en/guide/start/quick-start.mdx
apps/website-new/docs/zh/guide/basic/rspack.mdx
apps/website-new/docs/zh/guide/start/quick-start.mdx

Improve Rspack / Rsbuild plugin guide:
- Add example for registering the plugin in `rspack.config.ts`
- Improve the Rsbuild config example, make it easier to understand. For example, use the object format of `tools.rspack`.

docs: improve Rspack / Rsbuild plugin guide

---

.changeset/chilly-llamas-complain.md
apps/modernjs-ssr/dynamic-nested-remote/modern.config.ts
apps/modernjs-ssr/dynamic-nested-remote/package.json
apps/modernjs-ssr/dynamic-remote-new-version/modern.config.ts
apps/modernjs-ssr/dynamic-remote-new-version/package.json
apps/modernjs-ssr/dynamic-remote/modern.config.ts
apps/modernjs-ssr/dynamic-remote/package.json
apps/modernjs-ssr/host/modern.config.ts
apps/modernjs-ssr/host/package.json
apps/modernjs-ssr/nested-remote/modern.config.ts
apps/modernjs-ssr/nested-remote/package.json
apps/modernjs-ssr/remote-new-version/modern.config.ts
apps/modernjs-ssr/remote-new-version/package.json
apps/modernjs-ssr/remote/modern.config.ts
apps/modernjs-ssr/remote/package.json
apps/modernjs/package.json
packages/modernjs/package.json
packages/modernjs/src/ssr-runtime/plugin.tsx
pnpm-lock.yaml

chore: upgrade modernjs@2.57.0

---

.changeset/gold-clocks-suffer.md
packages/modernjs/src/cli/ssrPlugin.ts
packages/node/package.json

fix(modern-js-plugin): require node plugin on demand

---

apps/website-new/docs/en/guide/basic/_meta.json
apps/website-new/docs/en/guide/basic/error-catalog.mdx

This new doc is a collection of common error messages and solution paths to help beginners get their projects running with less headache.
Currently, there is no FAQ like section for common error patterns. I discussed this topic with @ScriptedAlchemy inside the Innovator Program. 
During my journey with ModuleFederation I will update this doc with all complex error messages I find and solve to pave the way for people new to ModuleFederation.
Related issue: https://github.com/module-federation/core/issues/2850

docs: add doc for error-catalog in "basic"

---

apps/website-new/docs/en/practice/bridge/index.mdx

small change - fix links for bridge examples
Fix links to repository examples.
I did not find a way to create a specific documentation issue.

docs: update index.mdx

---

.changeset/polite-toys-turn.md
apps/router-demo/router-host-2000/package.json
apps/router-demo/router-remote1-2001/rsbuild.config.ts
apps/website-new/docs/en/practice/bridge/index.mdx
apps/website-new/docs/en/practice/bridge/react-bridge.mdx
apps/website-new/docs/zh/practice/bridge/react-bridge.mdx
packages/bridge/bridge-react-webpack-plugin/package.json
packages/bridge/bridge-react-webpack-plugin/src/index.ts
packages/bridge/bridge-react-webpack-plugin/src/utis.ts
packages/bridge/bridge-react/package.json
packages/bridge/bridge-react/src/create.tsx
packages/bridge/bridge-react/src/remote/index.tsx
packages/bridge/bridge-react/src/router-v5.tsx
packages/bridge/bridge-react/src/router-v6.tsx
packages/bridge/bridge-react/vite.config.ts
packages/bridge/vue3-bridge/src/provider.ts
pnpm-lock.yaml

- [ x ] Docs change / refactoring / dependency upgrade
- [  ] Bug fix (non-breaking change which fixes an issue)
- [  ] New feature (non-breaking change which adds functionality)

chore: add english documentation for bridge chapter

---

packages/enhanced/src/lib/container/ContainerEntryModule.ts
packages/enhanced/src/lib/container/ContainerEntryModuleFactory.ts
packages/enhanced/src/lib/container/ContainerPlugin.ts
packages/enhanced/src/lib/container/FallbackModule.ts
packages/enhanced/src/lib/container/ModuleFederationPlugin.ts
packages/enhanced/src/lib/container/runtime/FederationRuntimePlugin.ts
packages/enhanced/src/wrapper/ModuleFederationPlugin.ts
packages/nextjs-mf/src/plugins/NextFederationPlugin/index.ts
packages/typescript/src/plugins/FederatedTypesPlugin.ts
pnpm-lock.yaml
webpack/lib/Compiler.d.ts
webpack/lib/Module.d.ts
webpack/lib/NormalModuleFactory.d.ts
webpack/lib/optimize/ConcatenatedModule.d.ts
webpack/lib/runtime/MfStartupChunkDependenciesPlugin.d.ts
webpack/package.json
webpack/types.d.ts

chore: fix package types with webpack

---

apps/router-demo/router-host-2000/package.json
packages/bridge/bridge-react-webpack-plugin/__tests__/mockRouterDir/router-v5/react-router-dom/package.json
packages/bridge/bridge-react-webpack-plugin/__tests__/mockRouterDir/router-v6/react-router-dom/package.json
packages/bridge/bridge-react-webpack-plugin/__tests__/utils.spec.ts
packages/bridge/bridge-react-webpack-plugin/project.json
packages/bridge/bridge-react-webpack-plugin/src/utis.ts
packages/bridge/bridge-react-webpack-plugin/vitest.config.ts
pnpm-lock.yaml

fix: fix router alias issue for react-bridge

fix: fix router alias issue for react-bridge

---

.changeset/warm-dryers-suffer.md
apps/website-new/docs/en/configure/index.mdx
packages/enhanced/src/lib/container/runtime/FederationRuntimePlugin.ts
packages/sdk/src/types/plugins/ModuleFederationPlugin.ts

feat(enhanced): add support for virtual runtime entrypoints

---

.changeset/yellow-bugs-poke.md
packages/runtime/src/core.ts
packages/runtime/src/global.ts
packages/runtime/src/module/index.ts
packages/runtime/src/plugins/snapshot/SnapshotHandler.ts
packages/runtime/src/plugins/snapshot/index.ts
packages/runtime/src/remote/index.ts
packages/runtime/src/utils/env.ts
packages/runtime/src/utils/preload.ts
packages/runtime/src/utils/tool.ts
packages/sdk/src/logger.ts
packages/sdk/src/utils.ts

remove duplicate functions from runtime and import them from sdk

fix(runtime): remove function duplication

---

webpack/lib/NormalModuleFactory.d.ts
webpack/types.d.ts

chore: import types from files

---

.github/workflows/e2e-next.yml
apps/manifest-demo/webpack-host/src/index.ts
apps/manifest-demo/webpack-host/src/index.tsx
apps/manifest-demo/webpack-host/webpack.config.js
packages/enhanced/src/lib/container/HoistContainerReferencesPlugin.ts
packages/webpack-bundler-runtime/package.json
packages/webpack-bundler-runtime/src/index.ts
pnpm-lock.yaml

enabel embedRuntime in manifest-webpack-host demo, and set runtimeChunk ,there are two different phenomena will occur: 
* `nx build manifest-webpack-host` : build sussess
* `nx serve manifest-webpack-host` : throw below errors

chore: enable embed runtime

---

packages/manifest/src/StatsManager.ts
packages/nextjs-mf/src/loaders/helpers.ts
packages/nextjs-mf/src/plugins/NextFederationPlugin/set-options.ts
packages/nextjs-mf/src/plugins/NextFederationPlugin/validate-options.ts
packages/nextjs-mf/src/plugins/container/InvertedContainerPlugin.ts
packages/nextjs-mf/src/plugins/container/InvertedContainerRuntimeModule.ts

fix some type imports from dead utils packages

chore: type fixes to next mf

---

package.json
packages/managers/package.json
packages/storybook-addon/package.json
pnpm-lock.yaml

chore: align webpack version

---

.changeset/perfect-spies-stare.md
packages/nextjs-mf/src/loaders/fixImageLoader.ts

fix(nextjs-mf): make CSR and SSR image loading consistent in next-mf (#2873)

---

apps/manifest-demo/3010-rspack-provider/rspack.config.js
apps/manifest-demo/3011-rspack-manifest-provider/rspack.config.js
apps/manifest-demo/3012-rspack-js-entry-provider/rspack.config.js
apps/react-ts-remote/rspack.config.js
package.json
pnpm-lock.yaml

fix: bump nx/rspack to latest for nx upgrade

---

packages/enhanced/src/lib/container/runtime/FederationRuntimePlugin.ts

simplify setRuntimeAlias logic

refactor(enhanced): simplify setRuntimeAlias function

---

apps/website-new/docs/en/plugin/plugins/retry-plugin.mdx
apps/website-new/docs/zh/plugin/plugins/retry-plugin.mdx

chore: fix docs error

---

packages/nextjs-mf/package.json
packages/runtime/package.json
packages/runtime/project.json
packages/runtime/rollup.config.js
packages/sdk/package.json
packages/sdk/project.json
packages/sdk/rollup.config.js
packages/webpack-bundler-runtime/package.json
packages/webpack-bundler-runtime/project.json
packages/webpack-bundler-runtime/rollup.config.js
pnpm-lock.yaml

bundle polyfills into shareable chunk per package to reduce duplication in every entry file that rollup emits

fix: bundle polyfills

---

.changeset/config.json

chore: add data prefetch into fixed

---

apps/website-new/docs/en/guide/framework/modernjs.mdx
apps/website-new/docs/zh/guide/framework/modernjs.mdx

fix: modernjs ssr demo is broken, should use main branch

---

.github/workflows/build-and-test.yml
.github/workflows/e2e-next-dev.yml
.gitignore
packages/data-prefetch/jest.config.js
packages/enhanced/jest.embed.ts
packages/enhanced/project.json
packages/enhanced/test/ConfigTestCases.embedruntime.js
packages/enhanced/test/ConfigTestCases.template.js
packages/enhanced/test/script-experiments.js
packages/enhanced/test/script.js

chore: fix hanging test pattern

---

ai-lint-fix.js
packages/enhanced/src/lib/container/HoistContainerReferencesPlugin.ts
packages/enhanced/src/lib/container/runtime/EmbedFederationRuntimeModule.ts
packages/enhanced/src/lib/container/runtime/EmbedFederationRuntimePlugin.ts
packages/nextjs-mf/src/plugins/NextFederationPlugin/next-fragments.ts

chore: code cleanup

---

README.md
apps/manifest-demo/README.md
apps/modernjs-ssr/README.md
apps/router-demo/README.md
apps/router-demo/router-host-2000/src/pages/Remote1.tsx
apps/router-demo/router-host-v5-2200/src/pages/Remote1.tsx
packages/bridge/bridge-react-webpack-plugin/README.md
packages/bridge/bridge-react/README.md
packages/bridge/bridge-shared/README.md
packages/chrome-devtools/README.md
packages/esbuild/.swcrc
packages/esbuild/README.md
packages/esbuild/src/adapters/lib/commonjs.ts
packages/manifest/README.md
packages/native-federation-tests/README.md
packages/native-federation-typescript/README.md
packages/nextjs-mf/README.md
packages/node/README.md
packages/retry-plugin/README.md

chore: format all files

---

packages/data-prefetch/__tests__/react.spec.ts
packages/data-prefetch/src/prefetch.ts

fix: data prefetch test

---

apps/website-new/docs/en/practice/bridge/react-bridge.mdx

At line 133, the loadRemote function will be undefined if it is not properly imported.

fix: Adds missing import of loadRemote

---

package.json
packages/esbuild/package.json
pnpm-lock.yaml

chore: update rollup

---

apps/modernjs-ssr/dynamic-nested-remote/.npmrc
apps/modernjs-ssr/dynamic-nested-remote/package.json
apps/modernjs-ssr/dynamic-remote-new-version/.npmrc
apps/modernjs-ssr/dynamic-remote-new-version/package.json
apps/modernjs-ssr/dynamic-remote/.npmrc
apps/modernjs-ssr/dynamic-remote/package.json
apps/modernjs-ssr/host/.npmrc
apps/modernjs-ssr/host/package.json
apps/modernjs-ssr/nested-remote/.npmrc
apps/modernjs-ssr/nested-remote/package.json
apps/modernjs-ssr/remote-new-version/.npmrc
apps/modernjs-ssr/remote-new-version/package.json
apps/modernjs-ssr/remote/.npmrc
apps/modernjs-ssr/remote/package.json
apps/modernjs/package.json
pnpm-lock.yaml

chore: update modernjs packages

---

package.json

limit engines range, incase local env is different from ci which can not easy to troubleshoot

chore: limit engines range

---

.changeset/config.json

fix @module-federation/rsbuild-plugin version

chore: fix @module-federation/rsbuild-plugin version

---

.changeset/happy-chefs-pay.md
packages/rsbuild-plugin/src/cli/index.ts
packages/rsbuild-plugin/src/utils/constant.ts
packages/rsbuild-plugin/src/utils/index.ts

Change default assetPrefix, do the same as [#3747](https://github.com/web-infra-dev/rsbuild/pull/3757)

fix: configure the default assetPrefix for MF apps correctly

---

apps/website-new/docs/en/guide/start/quick-start.mdx

Corrected small errors in one code example in the guide.

Corrected code example

---

apps/website-new/docs/en/guide/basic/error-catalog.mdx

Adding Error Catalog documentation for related open issues.
These issues were resolved via discussion but the results are good additions to the existing error catalog.
Please link to the issue here:  
#2827
#2672

docs: add docs for @mf-types related errors

---

.changeset/chilly-berries-look.md
packages/sdk/package.json
pnpm-lock.yaml

update to version that has types field on package.json

fix(sdk): update rslog to fix type error

---

packages/nextjs-mf/project.json

chore(nextjs-mf): remove old build paths from nx

---

.changeset/khaki-eggs-grab.md
packages/storybook-addon/src/utils/with-module-federation-enhanced-rsbuild.ts

fix: fix windows path error

---

.changeset/gorgeous-cups-perform.md
packages/sdk/package.json
pnpm-lock.yaml

remove meaningless log
https://github.com/2heal1/isomorphic-rslog/commit/84cc17e01a22dc543fb1f532991b69d104032c48
https://github.com/module-federation/core/issues/3182

fix: remove meaningless log

---

apps/website-new/docs/en/guide/basic/type-prompt.mdx
apps/website-new/docs/zh/guide/basic/type-prompt.mdx

add runtime api type hints tip
https://github.com/module-federation/core/issues/2921

docs: add runtime api type hints tip

---

apps/rslib-module/.storybook/main.ts
apps/rslib-module/README.md
apps/rslib-module/package.json
apps/rslib-module/project.json
apps/rslib-module/rslib.config.ts
pnpm-lock.yaml

update rslib demo usage
* add dev command

chore: update rslib demo

---

README.md

Adding Repobeat to the
Adding repobeat for nice visibility into contributors on readme.

chore(readme): repobeat

---

.changeset/great-glasses-retire.md
packages/chrome-devtools/manifest.json
packages/chrome-devtools/modern.config.ts
packages/chrome-devtools/project.json
packages/chrome-devtools/src/utils/chrome/fast-refresh-init.ts
packages/chrome-devtools/src/utils/chrome/snapshot-plugin-init.ts

immediately inject global runtime plugins
https://github.com/module-federation/core/issues/3287

fix: immediately inject global runtime plugins

---

packages/runtime/src/utils/load.ts

runtime lint fix
https://github.com/module-federation/core/actions/runs/12157379387/job/33903043268

chore(runtime): lint fix

---

apps/website-new/docs/en/guide/basic/runtime.mdx

Update types and add comments according to the current codes.
If any of the comments are incorrect or unclear, please leave a review comment.

docs: update shared type definitions in Federation Runtime

---

.changeset/nice-suns-eat.md
packages/data-prefetch/src/prefetch.ts

the prefetch exports type is promise or function

fix(data-prefetch): the prefetch exports type is promise or function

---

README.md

Link to CONTRIBUTING in README was to canary instead of main

fix(docs): adde correct contributing link to README

---

.changeset/orange-goats-hope.md

chore: downgrade changset version

chore: downgrade changset version

---

.github/workflows/release.yml

remove release with comment action

chore: remove release with comment

---

.changeset/neat-jars-type.md
packages/chrome-devtools/src/App.tsx
packages/chrome-devtools/src/component/Form/index.tsx
packages/chrome-devtools/src/component/Layout/index.tsx
packages/chrome-devtools/src/utils/types/common.ts

Support extended form option character validation.

feat(chrome-devtools): add customValueValidate

---

.changeset/lucky-shirts-listen.md
packages/sdk/package.json
pnpm-lock.yaml

chore: bump logger

---

apps/router-demo/router-host-2000/src/App.tsx

chore: fix ci failed issue

---

apps/website-new/docs/en/guide/troubleshooting/runtime/RUNTIME-008.mdx
apps/website-new/docs/zh/guide/troubleshooting/runtime/RUNTIME-008.mdx

feat(website): add Runtime-008 for trouble-shooting chapter

feat(website): add Runtime-008 for trouble-shooting chapter

---

apps/website-new/docs/zh/guide/framework/modernjs.mdx
apps/website-new/docs/zh/guide/framework/nextjs.mdx
apps/website-new/docs/zh/guide/start/index.mdx

chore: optimize cn website documentation in framework

chore: optimize cn website documentation in framework

---

.github/workflows/build-and-test.yml
.github/workflows/devtools.yml
.github/workflows/e2e-manifest.yml
.github/workflows/e2e-modern-ssr.yml
.github/workflows/e2e-modern.yml
.github/workflows/e2e-next-dev.yml
.github/workflows/e2e-next-prod.yml
.github/workflows/e2e-node.yml
.github/workflows/e2e-router.yml
.github/workflows/e2e-runtime.yml
.github/workflows/release-pull-request.yml
.github/workflows/release.yml

```
Error: Cannot find matching keyid: {"signatures":[{"sig":"MEQCIBfxS9RKPsi46jxBHnsGYQ03mg8um110415vE6KRCzY8AiBvik66sYxJ/NyCovwJSbDuuoaYCxc7EVdFhaaciIXjTw==","keyid":"SHA256:DhQ8wR5APBvFHLF/+Tc+AYvPOdTpcIDqOhxsBHRwC7U"}],"keys":[{"expires":null,"keyid":"SHA256:jl3bwswu80PjjokCgh0o2w5c2U4LhQAE57gj9cz1kzA","keytype":"ecdsa-sha2-nistp256","scheme":"ecdsa-sha2-nistp256","key":"MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE1Olb3zMAFFxXKHiIkQO5cJ3Yhl5i6UPp+IhuteBJbuHcA5UogKo0EWtlWwW6KSaKoTNEYL7JlCQiVnkhBktUgg=="}]}
```
https://github.com/nodejs/corepack/issues/616

fix: corepack signature error on ci

---

.github/workflows/issue-labeled.yml
.github/workflows/pr-label.yaml

chore: add permissions on workflow

---

apps/website-new/docs/en/blog/error-load-remote.mdx
apps/website-new/docs/zh/blog/error-load-remote.mdx

chore: add version limit explanation for remote module error handling blog.

chore: add version limit explanation for remote module error handling blog

---

apps/website-new/docs/en/index.md
apps/website-new/docs/zh/index.md
apps/website-new/theme/components/HomeFooter/index.tsx
apps/website-new/theme/pages/index.tsx

chore: delete contributors section for landing page due to unavailable cdn resources

chore: delete contributors section for landing page due to unavailable cdn resources

---

.github/dependabot.yml

Daily updates lead to too many invalid PRs, change to montly.
github doc ref: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#about-the-dependabotyml-file

chore: add dependabot config file and set interval to monthly

---

apps/website-new/docs/en/guide/start/index.mdx
apps/website-new/docs/en/guide/start/quick-start.mdx
apps/website-new/docs/zh/guide/start/index.mdx
apps/website-new/rspress.config.ts

chore: add lark group link

---

.changeset/calm-tigers-own.md
apps/router-demo/router-remote1-2001/package.json
packages/bridge/bridge-react/src/compat.ts
packages/bridge/bridge-react/src/provider.tsx
pnpm-lock.yaml

fix(bridge-react): the bridge-react package was failing when used with React 16/17 due to missing react-dom/client module.

fix(bridge-react): the bridge-react package was failing when used with React 16/17 due to missing react-dom/client module

---

apps/website-new/docs/en/guide/basic/runtime.mdx
apps/website-new/docs/zh/guide/basic/runtime.mdx

-  Updated the type of InitOptions in the runtime documentation for both Chinese and English.

doc:update runtime types

---

.changeset/orange-days-kiss.md
packages/dts-plugin/package.json
packages/dts-plugin/project.json
packages/dts-plugin/src/core/configurations/remotePlugin.test.ts
packages/dts-plugin/src/core/configurations/remotePlugin.ts
packages/dts-plugin/src/core/lib/DTSManager.advance.spec.ts
packages/dts-plugin/src/core/lib/DTSManager.general.spec.ts
packages/dts-plugin/src/core/lib/DTSManager.spec.ts
packages/dts-plugin/src/core/lib/typeScriptCompiler.test.ts
pnpm-lock.yaml

* add specify dir and mf name to cache path
* auto set remoteTypesFolder:false if enable incremental

fix(dts-plugin): add specify dir and mf name to cache path

---

.changeset/dry-geese-drum.md
packages/dts-plugin/src/core/lib/DTSManager.ts

consume api types if adding new one

fix(dts-plugin): consume api types if adding new one

---

.changeset/strong-ravens-push.md
packages/manifest/src/ManifestManager.ts
packages/manifest/src/StatsManager.ts
packages/manifest/src/logger.ts
packages/sdk/package.json
packages/sdk/src/logger.ts
pnpm-lock.yaml

chore: remove isomorphic-rslog

---

.changeset/fair-lies-move.md
packages/sdk/src/dom.ts

fix(sdk): createLink hook error dom attr rel

---

.changeset/dirty-pianos-learn.md
packages/node/src/utils/hot-reload.ts

delete server module cache if hot reload

fix(node): delete server module cache if hot reload

---

.changeset/nice-rice-count.md
packages/bridge/bridge-react/package.json
pnpm-lock.yaml

https://github.com/module-federation/core/issues/3609

fix(bridge-react): remove loadable/component dep

---

.changeset/tall-rivers-hope.md
packages/runtime-core/src/utils/share.ts

chore(runtime): remove shared strategy warn

---

packages/enhanced/src/schemas/container/ModuleFederationPlugin.check.ts
packages/enhanced/src/schemas/container/ModuleFederationPlugin.json
packages/enhanced/src/schemas/container/ModuleFederationPlugin.ts
packages/enhanced/src/scripts/compile-schema.js

chore: fix schema

---

.github/workflows/e2e-modern-ssr.yml

chore: optrimize modernjs ssr ci

---

packages/chrome-devtools/src/utils/sdk/index.ts

feat: vue hmr

---

apps/website-new/docs/en/blog/error-load-remote.mdx
apps/website-new/docs/zh/blog/error-load-remote.mdx

chore: update local backup manifest data with effective mock data

chore: update local backup manifest data with effective mock data

---

.changeset/chilled-plums-arrive.md
packages/manifest/src/ManifestManager.ts

feat(manifest): initialize manifest with required properties from stats.

feat(manifest): initialize manifest with required properties from stats

---

apps/website-new/docs/en/configure/shared.mdx
apps/website-new/docs/zh/configure/shared.mdx

docs: add shared import

---

.changeset/silent-seas-flow.md
packages/managers/src/BasicPluginOptionsManager.ts
packages/managers/src/PKGJsonManager.ts
packages/managers/src/SharedManager.ts

feat(managers): add root option

---

.changeset/nervous-cougars-heal.md
packages/rsbuild-plugin/package.json
packages/rsbuild-plugin/src/cli/index.ts
pnpm-lock.yaml

* detect server.cors option to check waring
* fix warning message typo

fix(rsbuild-plugin): detect server.cors option to check waring

---

.changeset/beige-apricots-switch.md
.changeset/rare-rockets-wink.md
packages/dts-plugin/src/plugins/DevPlugin.ts
packages/modernjs/src/cli/configPlugin.ts

only inject ipv4 str in dev mode

fix: only inject ipv4 str in dev mode

---

.changeset/weak-spoons-begin.md
packages/modernjs/src/cli/mfRuntimePlugins/auto-fetch-data.ts
packages/node/src/runtimePlugin.ts

If the remote not have ssr asset, the fetch type should be FETCH_CLIENT

fix(modern-js-plugin): adjust fetch type

---

apps/website-new/package.json
pnpm-lock.yaml

docs: upgrade Rspress@2.0.0-beta.14

---

apps/website-new/docs/en/guide/basic/cli.mdx
apps/website-new/src/components/common/cli/view-all-cmds-en.mdx

docs: translate cli component

---

packages/chrome-devtools/src/App.tsx
packages/chrome-devtools/src/component/Form/index.module.scss
packages/chrome-devtools/src/component/Form/index.tsx
packages/chrome-devtools/src/component/Layout/index.tsx
packages/chrome-devtools/src/utils/types/common.ts

chrome devtool add header slot

feat: devtool add header slot

---

apps/website-new/docs/en/practice/frameworks/next/index.mdx

Fix typo in badge label: "Reccomended" → "Recommended"

docs(next): correct typo in recommended badge

---

packages/runtime-core/src/plugins/generate-preload-assets.ts

Don't need to enter the block if remote doesn't have any shared.

refactor: check if remote has any shared modules

---

apps/website-new/docs/en/guide/framework/modernjs.mdx
apps/website-new/docs/en/practice/bridge/react-bridge.mdx
apps/website-new/docs/zh/guide/framework/modernjs.mdx
apps/website-new/docs/zh/practice/bridge/react-bridge.mdx

add createRemoteCompoent and createRemoteSSRComponent deprecated documentation

docs: add createRemoteCompoent and createRemoteSSRComponent deprecated documentation

---

apps/website-new/src/components/en/data-fetch/consumer.mdx
apps/website-new/src/components/zh/data-fetch/consumer.mdx

docs: remove unused constant

---

.changeset/tidy-buttons-listen.md
package.json
packages/dts-plugin/package.json
packages/native-federation-tests/package.json
packages/native-federation-typescript/package.json
pnpm-lock.yaml

This PR updates `axios` to a version that no longer relies on a vulnerable `form-data` dependency.
- Upgraded `axios` to the latest secure version.
- Ensures `form-data` is updated to a version without known security vulnerabilities.
- No functional or breaking changes are expected.
Closes https://github.com/module-federation/core/issues/3999

chore: bump axios to resolve vulnerabilities in form-data dependency

---

apps/website-new/package.json
pnpm-lock.yaml

fix: lock website react version

---

packages/native-federation-tests/CHANGELOG.md
packages/native-federation-tests/package.json
packages/native-federation-typescript/CHANGELOG.md
packages/native-federation-typescript/package.json
packages/typescript/CHANGELOG.md
packages/typescript/package.json

bump pkg versions: @module-federation/native-federation-tests 、@module-federation/native-federation-typescript 、@module-federation/typescript

chore: bump

---

.changeset/polite-years-leave.md
packages/dts-plugin/src/plugins/GenerateTypesPlugin.ts

correct generateTypes host params

fix(dts-plugin): correct generateTypes host params
