module-federation/core

- README.md
- bin/nextjs-mf.js
- package.json
Adding a `nextjs-mf` command line function that you can use on a fresh `create-next-app` and upgrade it to support Module Federation.
> Adding a command line easy upgrade

- README.md
- merge-runtime.js
Hello, I updated 2 things to avoid to declare the "_next" in the webpack conf of the host.
1. I move the merged runtime in the "runtime" folder
2. I deleted the lines of the documentation setting the publicPath
This way, the consumer app can use the remote file in http://localhost:3000/_next/static/runtime/remoteEntryMerged.js.
> fix(publicPath): enable auto value

- package.json
This Fixes the issue #27 
Commander is required as dependencies in order to upgrade
> fix(command): Move commander as dependencies

- merge-runtime.js
- patchSharing.js
**When module federation is used between 2 nextjs apps the function `patchSharing` errors as `__non_webpack_require__` can be undefined.  This work resolves that issue.**
**When `mergeRuntime` is enabled in next.config.js for two apps using module federation the build fails as a filename can be undefined when one or more apps does not expose remote files.  This work fixes that issue.**
### With current code:
> fix nextjs module federation 

- next_router_context.js
- withModuleFederation.js
Should fix #37 and #26 . This shares the router from the main app in all other modules. Otherwise the router is not properly initialized in external modules.
> (fix) Use same next router in all modules

- merge-runtime.js
- withModuleFederation.js
This enables the use of custom name. 
On my side, I add some build variables such as NEXT_PUBLIC_* env values.
> fix(remoteEntry): enable custom name

- README.md
In a production build the folder `server/static/runtime/remoteEntry.js` does not exist for SSR. As far as I understand it, you should use the chunks instead. Added this to the readme
> docs: Use chunks in production builds

- withModuleFederation.js
When I run this locally the `require.resolve` works fine, but when I put the frontends into docker containers and load the `static/runtime/remoteEntry.js` it fails because the external uses an absolute path in there. 
This changes the `require` in the `remoteEntry.js` from
```
module.exports = require("/Users/<path-to-project>/node_modules/@module-federation/nextjs-mf/react.js");
```
to
```
module.exports = require("@module-federation/nextjs-mf/react.js");
```
> fix: Use module path for react external

- README.md
- lib/with-federated-sidecar.js
- package.json
in prod mode, next has limitations due to how chunking and tree shaking + sync bootup + aliasing. 
To work around this, we assign internal modules to the share scope at the very start of the application. This is the low-level equivalent of `eager:true` but without altering the chunking mechanism. 
This is okay to do because you will ever only want to use host-only copies of next internals, so re-attaching them to share scope at runtime is fine. 
Eager sharing causes the modules to move around and usually another copy is created in the remote container to ensure its availability. We can replicate this functionality without moving the modules out of the framework bundle by requiring them like normal
> update docs to reflect next internal module sharing

- README.md
- demo/3000-home/next.config.js
- src/NextFederationPlugin.js
Adds a new extra option, `skipSharingNextInternals` which the default behavior of sharing common nextjs modules when specified. This is useful in cases where explicit control of shared modules is helpful, such as with a react host and nextjs child application.
Fixes https://github.com/module-federation/nextjs-mf/issues/140
> feat: Add skipSharingNextInternals extraOption

- src/NextFederationPlugin.js
Resolves #136
Use library type `window` instead of `var` to avoid topLevel mangling 
This assigns remote to window scope object
> fix: prevent SWC mangle of remote global

- demo/3001-shop/pages/shop/index.js
- node-plugin/streaming/NodeRuntime.js
- src/NextFederationPlugin.js
resolves: #157 
Current implementation introduces a new type of problem. Nested remote attempts to use a promise as url to load container. Some bugs to still resolve here.
> Fix nested remote imports

- demo/3000-home/next.config.js
- demo/yarn.lock
- node-plugin/streaming/LoadFileChunkLoadingRuntimeModule.js
- node-plugin/streaming/NodeRuntime.js
Remotes typically do not know their own URL;
home usually wont have itself listed as a remote, but shop would have home as a remote. 
When loading home, the container needs a way to know its absolute URL path in order to load the federated module chunks. 
To do so, we want each host/remote to register all its @ syntax configs to a global object - this way, a remote can look itself up by name and find the URL from its parent. 
Since versioned remotes is possible, we want to look up by global name, there should only ever be one global or a URL just like in the browser. So this is a safe operation as collisions here would be the same as collisions in the browser.
https://youtu.be/cQawWpUl8ro
> [SSR] Global remote config registry

- src/NextFederationPlugin.js
This PR addresses the following scenario:
`Host`: Next.js
`Remote1`: Basic React
`Remote2`: Basic React
- `Remote2` defines a button component and exposes it.
- `Remote1` exposes a composed button component, leveraging `Remote2`'s button as a base
- `Host` consumes both buttons on the same page
Without this PR modification, you'll encounter two errors
```
TypeError: Cannot create proxy with a non-object as target or handler
at Object.init (test.js?ts=1662739775572:126:26)
at test.js?ts=1662739775572:134:15
at async Promise.all (index 0)
Error: Container initialization failed as it has already been initialized with a different share scope
at Object.init (container_entry:22:48)
at Object.init (test.js?ts=1662739775572:191:21)
at initFn (webpack.js?ts=1662739775572:390:86)
at async …
```
> fix: container initialization failed - different share scope

- demo/3000-home/pages/_menu.js
- demo/3000-home/pages/home/test-broken-remotes.js
- demo/mfRoutes.js
- src/client/MFClient.ts
- src/client/RemotePages.ts
- src/loaders/patchNextClientPageLoader.js
If remoteEntry or module are unavailable then reload a page and try to get its server version.
I have 20 nextjs apps and I met with a migration issue. I cannot update all applications instantly. So if one of the application does not expose remoteEntry then we need just to reload the page and the Load balancer will serve the correct application. Like it works now with NextJS [Multi Zones](https://nextjs.org/docs/advanced-features/multi-zones).
With this fix, I will be able to migrate and update applications separately. And some transitions between apps will be with page reloads others without.
-----
> fix(MFClient): correctly handle routeInfo loading errors

- demo/3000-home/next.config.js
- demo/3001-shop/next.config.js
- demo/3001-shop/pages/shop/index.js
- demo/package.json
- demo/tmp/nextjs-mf/package.json
- demo/yarn.lock
- package.json
- rollup.config.js
- src/NextFederationPlugin.js
- src/build-utils.js
- src/index.js
- src/internal.js
- src/loaders/fixImageLoader.js
- src/utils.js
- yarn.lock
Adds support for complex promise factories in userland. 
```js
remotes: {
shop: promiseTemplate(
// remote entry must always be the first promise
(resolve, reject) => {
resolve('shop@http://localhost:3001/_next/static/chunks/remoteEntry.js');
},
(resolve,reject)=>{
console.log('runing other promise');
setTimeout(() => {
console.log('resolving promise');
resolve();
} , 1000);
}),
checkout: "checkout@http",
shop: promiseTemplate(
// can also be a string if it needs to be computed in scope
`(resolve, reject) => {
resolve("${remotes.shop}");
}`,
(resolve,reject)=>{
console.log('runing other promise');
setTimeout(() => {
console.log('resolving promise');
resolve();
} , 1000);
}),
another: promiseTemplate(
'another@http://localhost:3001/_next/static/chunks/remoteEntry.js',
(resolve,reject)=>{ …
```
> Custom promises from userland

- packages/nextjs-mf/package.json
- yarn.lock
`nextjs-mf` package currently includes `next@11.0.1` as a **peer dependency** which is not the latest version.
> feat: update the `next` peer dep in nextjs-mf

- packages/node/src/plugins/LoadFileChunkLoadingRuntimeModule.ts
Update path to Webpack's HMR runtime to not depend on relative paths.
This is the same change made in the [module-federation/node](https://github.com/module-federation/node) repo.
Apparently, the change was lost during the relocation.
See related issue and PR:
- https://github.com/module-federation/node/issues/7
- https://github.com/module-federation/node/pull/8
> fix(node): fix path to webpack hmr runtime

- packages/node/src/plugins/UniversalFederationPlugin.ts
```
ValidationError: Invalid options object. Module Federation Plugin has been initialized using an options object that does not match the API schema.
- options has an unknown property 'isServer'.
```
Above error was thrown when passing isServer to the plugin due to the whole options object got passed further to ModuleFederationPlugin & isServer was not a valid option. Just need to extract it out & pass through the rest.
https://github.com/module-federation/node/pull/17
> Fix webpack validation error with UniversalFederationPlugin

- packages/utilities/src/types/index.ts
- packages/utilities/src/utils/common.ts
My application needs to swap out the same global with different remotes. Adding a unique key to optionally override the default container key allows us to load in the new remote when necessary.
> Adds unique key override to injectScript

- packages/node/src/utils/hot-reload.js
Add node-fetch fallback in node hot-reload util.
As global fetch is available in Node.js v18+, this code throws an error in previous Node.js versions as `fetch` is `undefined`.
Uses the same approach as NodeFederationPlugin [here](https://github.com/apehead/nextjs-mf/blob/4a5e2824400cc843fa0c0504936a68c6c9f33946/packages/node/src/plugins/NodeFederationPlugin.ts#L56).
> fix(node): add node-fetch fallback in node hot-reload util

- packages/nextjs-mf/utils/index.ts
- yarn.lock
Ensure css links are rendered into the head. Ensure that when remote entry js is server rendered is includes a datestamp to cache bust it
> fix: flush CSS chunks, cache bust remote entry on render

- packages/typescript/src/lib/Typescript.ts
When downloading the types from a remote, we need to preserve the folder structure of those components to avoid name collisions. 
Take this for example, remote-1 exposes the following: 
```
| - Accordion
|   | - Item.d.ts
|   | - Header.d.ts
|   | - index.d.ts
| - Markdown
|   | - Primitive.d.ts
| - Spinner
|   | - index.d.ts
| - Combobox
|   | - index.d.ts
| - Dialog
|   | - index.d.ts
| - Icon
|   | - index.d.ts
| - __types_index.json
```
Many of these files have `index.d.ts`. You'll notice that the result of downloading the types on the consumer  is incorrect due to the name collision:
```
| - remote-1
|   | - Item.d.ts
|   | - Header.d.ts
|   | - Primitive.d.ts
|   | - index.d.ts
```
Once my small fix is applied to preserve the folder structure, you'll end up with the following result …
> fix: preserve path of exposed `.d.ts` files

- packages/node/src/plugins/NodeFederationPlugin.ts
- packages/node/src/plugins/StreamingTargetPlugin.ts
- packages/utilities/package.json
- packages/utilities/src/utils/common.ts
- packages/utilities/src/utils/react.tsx
Node plugin adds additional copies of readFileVM when not in child compiler if enabledLibraryTypes is unset
> fix: fix node plugin fs augments when outside next child compiler

- packages/typescript/README.md
- packages/typescript/src/lib/Typescript.ts
I thought it would make sense to have the output mirror the `exposes` keys (public path) as opposed to the original source path. e.g.
```js
// "expose/public/path": "source/path",
"./atoms/Counter": "lib/Counter",
"./molecules/Header": "lib/Header",
```
now gives
```
@mf-typescript/
├─ atoms/
│  ├─ Counter.d.ts
├─ molecules/
│  ├─ Header.d.ts
```
With this change, the federated module imports now match the type definition folder structure
```js
import Header from '[remote]/molecules/Header';
// types can be found in `@mf-typescript/[remote]/molecules/Header.d.ts`
```
so instead of manually importing the types and casting with `as unknown as typeof CounterType`, we can add `@mf-typescript` to the `paths` array in `tsconfig.json` and all the types will picked up by the compiler
```json
{ …
```
> (typescript) Use expose public path as basis for @mf-typescript output structure

- packages/nextjs-mf/README.md
Update docs to address issue https://github.com/module-federation/nextjs-mf/issues/305
> docs: update docs, `options.isServer` no longer needed

- packages/utilities/src/Logger.ts
- packages/utilities/src/index.ts
Usage:
In the `webpack plugin#apply` method, extract `infrastructure logger` and set it to the logger constructor
```typescript
import type { Compiler } from 'webpack';
import { Logger } from '@module-federation/utilities';
class SomePlugin {
apply(compiler: Compiler) {
this.logger = Logger.setLogger(
compiler.getInfrastructureLogger(PLUGIN_NAME)
);
// somewhere else in the plugin
this.logger.log("do the log here");
}
}
```
closes #243
> feat(utils): configurable logger using webpack infrastructure logger

- packages/node/src/utils/hot-reload.ts
> fix: hot-reload not working when node-fetch is imported from require()

- packages/typescript/src/lib/Typescript.ts
Hello
~~This PR seeks to propagate errors when `ts.createProgram().emit()` fails. Essentially Typescript errors, that are not immediately obvious to the user as declaration emit is done with a separate set of rules from their local tsconfig.json ruleset. If this step currently fails further failures will continue in the plugin since `importRemoteTypes()` depends on this step being complete.~~
Moreover, I add the option of including additional files in this step, besides those referenced by `"ModuleFederationPluginOptions.remotes"`. This is particularly useful if the user has global declaration files (think `declaration.d.ts`, `dom.d.ts`, etc.), that are not imported or directly referenced in the code.
> Feat: Typescript -emit error handling, and options for the Typescript compiler

- .github/workflows/pre-release.yml
- .github/workflows/release.yml
Currently, all packages within the repository gets published to NPM whenever a  PR gets merged into the `main` branch.
Although this workflow achieves `Continuous Deployment`, it also poses an issue where one/more of the other packages might not be ready to be published especially in scenarios for **`BREAKING CHANGES`** as described in #299.
This PR addresses the issue by manually releasing package(s) by choosing which package to be released at release time.
For more information on how the workflow will work can be found in the [GitHub Actions Documentation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch)  
fixes #299
> ci: publish individual packages manually

- packages/node/src/plugins/CommonJsChunkLoadingPlugin.ts
- packages/node/src/plugins/LoadFileChunkLoadingRuntimeModule.ts
- packages/node/src/plugins/StreamingTargetPlugin.ts
- packages/node/src/plugins/UniversalFederationPlugin.ts
- yarn.lock
Currently, a high level of logging is produced when using the `module-federation/node` package.
This creates an unnecessary amount of noise, especially for production environments.
The logging is still useful for debug purposes however, so it should not be completely removed. 
This PR introduces a `verbose` flag that defaults to `false` to allow building production builds. If debugging is still required, you can set `verbose` to true in the options for the plugins.
> feat(node): add flag to control logging

- packages/nextjs-mf/src/loaders/fixImageLoader.ts
this pr will calculate the ssr images relative to the remote entry package instead of getting the origin,
so as long as the file system will be exactly as next dist directory, it will work
#392
> fix: support images for storages and local debug

- packages/node/src/plugins/LoadFileChunkLoadingRuntimeModule.ts
A mistake was made in the _getLogger function which led to inverted expectations from the verbose flag
> fix(node): verbose false should not log

- packages/typescript/src/plugins/FederatedTypesPlugin.ts
FederatedTypesPlugin was throwing an empty error when encountered an error, It wassn't possible to see the error unless we dig into the node_modules folder and throw the correct error.
> fix: throw correct error object instead of an empty error in FederatedTypesPlugin

- package.json
- packages/typescript/src/plugins/FederatedTypesStatsPlugin.ts
- yarn.lock
Fix for - https://github.com/module-federation/nextjs-mf/issues/393
The FederatedTypesStatsPlugin was being invoked twice, the second invocation did not have the federate type map set properly. Changing the webpack hook seemed to resolve the issue. I am unsure on the testing permutations on this particular fix, but testing it against a simple react application yielded good results.
> fix: cannot convert undefined object (Typescript package)

- packages/nextjs-mf/README.md
This PR fixes the path for `include-defaults` in the examples
I've noticed in the latest version of nextjs-mf v5.12.9, the lib folder is no longer in the package, and instead, there's a src folder with the `include-defaults.js`
> docs(nextjs-mf): fix path to include-defaults

- packages/typescript/src/lib/TypescriptCompiler.ts
Fixes #408
The `moduleResolution` and `target` options being passed to the TS compiler weren't valid.  Inside the `tsconfig.json`, they are strings, but the compiler expects enums.  This fix normalizes the values after the tsconfig is read from file.
> fix(typescript): fix parsing of tsconfig options for compiler

- packages/typescript/src/lib/normalizeOptions.ts
The typescript plugin merges the application's `tsconfig.json` with the default options in `normalizeOptions.ts`.
When `noEmit: true` is set in the applications tsconfig the plugin fails to emit any types, as is the expected behaviour from the TS compiler. This PR sets `noEmit` to `false` so that the plugin always emits the types, similar to the other defaults of `emitDeclarationOnly` and `declaration`
> fix(typescript): set noEmit: false when compiling types

- packages/typescript/src/lib/normalizeOptions.ts
- packages/typescript/src/plugins/FederatedTypesPlugin.ts
- packages/typescript/src/plugins/FederatedTypesStatsPlugin.ts
Currently the FederatedTypesStatsPlugins.js is hard coded to look for "remoteEntry.js", making a remote who uses a different filename in it's MF configuration always return a 404 while searching for the type stats json file.
The code below is the culprit:
```javascript
const typesStatsFileName = remoteEntryFilename
? remoteEntryFilename.replace('remoteEntry.js', TYPES_INDEX_JSON_FILE_NAME)
: TYPES_INDEX_JSON_FILE_NAME;
```
After removing this code, the typesStatsFileName variable is no longer needed at all. The fully qualified URL is generated in the FederateTypesPlugin with the following code, this would grab the URL stripping off the remote JS file and then concatenates the TYPES_INDEX_JSON_FILE_NAME to the end of it which is the same result.
```javascript
const remoteUrls = …
```
> fix: Typescript - Allow custom remote filename

- packages/nextjs-mf/src/loaders/async-boundary-loader.ts
> fix(async-boundary-loader): use relativeResource instead of this.resouce

- packages/typescript/src/lib/normalizeOptions.ts
- packages/typescript/src/plugins/FederatedTypesStatsPlugin.ts
Typescript artifacts - @mf-types folder and type stats json should be generated based on the relative path provided in the federatedConfig fileName property. This change moves both artifacts to the filename's relative path on the generation (remote) side:
Examples:
- static/chunks/remoteEntry.js -> static/chunks/@mf-types/*, static/chunks/__type_stats.json
- remoteEntry.js -> @mf-types/*, __type_stats.json (no base path - react test)
- test/remoteEntry.js -> test/@mf-types/*, test/__type_stats.json
There is a regression from [this change](https://github.com/module-federation/universe/pull/413), and this fix additionally moves the @mf-types into the same directory. With [the PR above](https://github.com/module-federation/universe/pull/413), types are fetched from the origin in the host …
> Typescript - use filename path for types

- packages/nextjs-mf/src/plugins/ChildFederationPlugin.ts
I noticed in the `nextjs` example in the examples repo, none of the files were being compiled into the `static/chunks` directory.  This appears to be due to the child compiler not running when `isServer=false`.  I've fixed the condition so that `childCompiler.run(...)` will run when `isServer=false`.
> fix(nextjs-mf): fix client-side compilation

- packages/utilities/src/index.ts
- packages/utilities/src/types/global.d.ts
- packages/utilities/src/types/index.ts
- packages/utilities/src/utils/importRemote.ts
This is a quick port [from the Utilities repo](https://github.com/module-federation/utilities/tree/main/runtime/importRemote). 
@ScriptedAlchemy - curious on your thoughts here, this module works great for pure react, the existing FederationBoundary module in utilities is dependent on next/dynamic and won't run in react. It might be worth keeping them separate long term. What do you think of keeping both but maybe updating the name?
> Add import remote from Utilities repo

- packages/nextjs-mf/src/include-defaults.ts
- packages/utilities/src/utils/importRemote.ts
bad references in utils to webpack globals
lazy import styled jsx and styles in the event its not used
> fix: bad references to webpack globals

- packages/nextjs-mf/project.json
Fixes #460
I suspect the issue may be caused because the npm release process is depending on a build output that doesn't factor in the package version uprev and the newly built dependent packages.  The current GHA builds the library in the `Build` step before `node` and `utilities` are built in the `Version` step, which I believe is causing the dependency mismatch.
> ci: git tags should match with release versions

- packages/typescript/README.md
- packages/typescript/src/constants.ts
- packages/typescript/src/lib/TypescriptCompiler.ts
- packages/typescript/src/lib/normalizeOptions.ts
- packages/typescript/src/types/index.ts
Addresses https://github.com/module-federation/universe/issues/411#issuecomment-1364024929
Inspired by the output that [dts-loader](https://github.com/ruanyl/dts-loader) has, it should eliminate most, if not all, issues related to the types output as this pr no longer tampers with the default typescript output behaviour. 
Default compilation compiles into `@mf-types/_types`. Then separately, anything defined in `exposes` will have a file created in `@mf-types`, which allow imports that match the desired expose paths.
```js
exposes: {
"./fetch-keys": "./lib/swr-fetch-keys",
"./footer": "./components/Footer",
},
```
In the screenshot above, you can see that entry points exist for the keys in `exposes` e.g. `./footer`, and this file re-exports `@mf-types/_types/components/Footer` as …
> typescript: fix @mf-types output when exposed component has imports

- .github/workflows/release.yml
- apps/react-ts-host/package.json
- apps/react-ts-remote/package.json
- packages/nextjs-mf/README.md
- packages/nextjs-mf/src/internal.ts
- yarn.lock
BREAKING-CHANGE: Previously, we used to "rekey" all shared packages used in a host in order to prevent eager consumption issues. However, this caused unforeseen issues when trying to share a singleton package, as the package would end up being bundled multiple times per page.
As a result, we have had to stop rekeying shared modules in userland and only do so on internal Next packages themselves.
If you need to dangerously share a package using the old method, you can do so by using the following code:
```js
const shared = {
fakeLodash: {
import: "lodash",
shareKey: "lodash",
}
}
```
Please note that this method is now considered dangerous and should be used with caution.
BREAKING CHANGE: Previously, we used to "rekey" all shared packages used in a host in order to prevent eager …
> feat: change module sharing strategy

- packages/utilities/package.json
The current webpack peer dep in the release is pinned to `5.74.0`.  This change will loosen the deps so that anything `^5.40.0` is allowed.  `5.40.0` was chosen to match the peer deps of the other packages.
> fix(utilities): set webpack peer dep to ^5.40.0

- packages/utilities/project.json
Currently, `tslib` is set as a peer dep in `utilities`, but this should be more appropriate as a regular dependency, similar to the other packages.
> fix(utilities): move tslib from peer deps into deps

- packages/typescript/src/lib/TypescriptCompiler.ts
- packages/typescript/src/lib/generateTypesStats.ts
Declaration files for defined exposes are now written to the types index JSON file referenced by consumers.
#486
> fix(typescript): defined exposes declaration files now consumable

- packages/typescript/src/plugins/FederatedTypesPlugin.ts
- yarn.lock
url derived from remote components urls previously failed when fetching types when package has an organization scope. by taking the split index and taking a substring of the remote url at that index fixes this issue
fix #495
> fix(federatedtypesplugin): modify remote url used to import remote types

- packages/typescript/src/plugins/FederatedTypesPlugin.ts
- packages/typescript/src/plugins/FederatedTypesStatsPlugin.ts
Fix for #455 - in the case of multiple remotes, the compiler callback was being called while it was still running. Made a small refactor to push the callback out of the importRemoteTypes method which also removes the any type. The stats plugin was also using a tapAsync but was not actually using a promise
Verified testing in a separate repo, running nx build typescript and next:start in the repo.
> Typescript - fix child compiler already started

- packages/nextjs-mf/utils/index.ts
This fixes FlushedChunks so it can be used in a TS project.  It currently throws this error when trying to use it.
```
'FlushedChunks' cannot be used as a JSX component.
Its return type 'any[]' is not a valid JSX element.
```
I've changed the code so that it wraps the children within a fragment so that the correct type can be inferred.  I've also fixed the props declaration.
> fix(nextjs-mf): fix FlushedChunks TS declaration

- packages/nextjs-mf/utils/build-utils.ts
Prevent webpack from crashing if remote isnt online, instead return a empty remote interface
> fix: resolve fake remote if offline

- packages/nextjs-mf/utils/index.ts
This fixes the "Each child in a list should have a unique "key" prop" warning.
> fix(nextjs-mf): fix list key warning in FlushedChunks

- packages/typescript/src/plugins/FederatedTypesPlugin.ts
Rather than throwing a confusing type error 'Cannot convert undefined or null to 
object'  when  no  `statsJson`  is found, `importRemoteTypes` now logs message and  
allows webpack to continue.
fix #498
> fix(typescript): in importRemoteTypes, if no statsJson found, log not found, and continue

- apps/3000-home/next.config.js
- apps/3000-home/remote-delegate.js
- packages/utilities/src/utils/common.ts
Move webpack_require calls from remote-delegates into the utilities, attempting to make injectScript a bit simpler, but provide a separate entry point for importDelegateModules.
Open to refactoring this a bit differently, I did not immediately know how to test injectScript outside of testing the next sample apps.
> Move remote-delegate logic into utilities

- packages/typescript/src/plugins/FederatedTypesPlugin.ts
According to #489, and reproducible on my windows machine, the regular expression generated for watch options does not compile correctly. 
https://webpack.js.org/configuration/watch/#watchoptionsignored - The webpack documentation looks as if you can just supply a folder and we don't need to supply wildcard glob matchers. This seemed to fix it on my windows machine - @pavandv, does this seem to make sense to you?
As far as testing, I created a @mf-types folder, added a file under it and edited it, webpack did not kick off any further compilations.
> Remove wildcards from regex watch options

- packages/typescript/src/lib/TypescriptCompiler.ts
Windows machines resolve paths with a separator of '\\', this causes a miss in the exposed component map in the TypescriptCompiler. This PR will replace '\\' with '/' for the exposed component map. Without the fix the exposed component was never generated.
> Typescript - ensure consistent file paths

- packages/typescript/package.json
- packages/typescript/src/lib/TypescriptCompiler.ts
- packages/typescript/src/types/index.ts
Change `vue-tsc` to be an optional peer dep otherwise react projects would have to include this unneeded dep.  I've also removed `next` and `react` from the peer deps since they both aren't a requirement to use this lib.
> fix(typescript): set vue-tsc as optional peer dep

- package.json
- packages/typescript/src/lib/download.ts
- packages/typescript/src/plugins/FederatedTypesPlugin.ts
- yarn.lock
Fixes #490
`download` isn't maintained anymore. There was an attempt to fix some of these issues in https://github.com/kevva/download/pull/220, but there's no activity from the maintainer.
This PR replaces `download` with a simple local function that uses `node-fetch`.
> fix(typescript): use node-fetch to download TS types

- packages/typescript/src/lib/TypescriptCompiler.ts
This fixes an issue where the import paths in the generated re-export dts file are incorrect on Windows.  The code checks if the platform-specific separator is a backslash, then replaces it with forward slashes so the imports are correct.
This is the output on `@module-federation/typescript` v2.2.0:
```
export * from './_types\Button';
export { default } from './_types\Button';
```
With fix:
```
export * from './_types/Button';
export { default } from './_types/Button';
```
> fix(typescript): fix import path for generated dts in Windows

- packages/typescript/src/lib/download.ts
Fixes #595
This falls back to the `pipeline` API that's available in Node 14
> fix(typescript): fix Node 14 compatibility

- packages/nextjs-mf/src/plugins/NextFederationPlugin.ts
Motivation:
When the project uses the 'src' folder, the NextFederationPlugin does not include the 'include-defaults.ts'! 
If we try to use a component like 'next/link' for example, it causes a runtime error in the application.
`Unhandled Runtime Error
Error: Shared module next/link doesn't exist in shared scope default`
Note:
Using the 'src' folder in the project is defined in the `yarn create next-app` wizard:
`Would you like to use `src/` directory with this project? › No / Yes`
> fix: include src folder in paths validation

- apps/3000-home/remote-delegate.js
- packages/nextjs-mf/src/internal.ts
- packages/nextjs-mf/src/plugins/ChildFederationPlugin.ts
- packages/nextjs-mf/src/plugins/NextFederationPlugin.ts
- packages/node/src/plugins/NodeFederationPlugin.ts
- packages/node/src/utils/hot-reload.ts
This PR enables Medusa Support in NextFederationPlugin by removing the dependency on the _medusa property and instead using a global variable to check if MedusaPlugin is present. This PR also simplifies the logic for parsing remote syntax and shared options, and fixes some typos and formatting issues in the code comments.
> feat: updating child compiler rules to support medusa

- packages/nextjs-mf/src/plugins/NextFederationPlugin.ts
This is an update to apply the exclude rule to /pages/middleware
> fix: exclude next middleware from async boundary loader

- packages/nextjs-mf/src/internal.ts
This enables us to have both the host and the remote be running in dev mode.
> fix: Add 'react/jsx-dev-runtime' to share scope

- packages/native-federation-typescript/src/lib/typeScriptCompiler.ts
> fix(native-federation-typescript): vue-tsc is now optional

- packages/nextjs-mf/CHANGELOG.md
- packages/nextjs-mf/package.json
- packages/nextjs-mf/src/internal.ts
- packages/nextjs-mf/src/plugins/NextFederationPlugin/apply-server-plugins.ts
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/utilities/CHANGELOG.md
- packages/utilities/package.json
- packages/utilities/src/utils/common.ts
This update focuses on resolving build issues and optimizing the handling of Next.js and React modules within the NextFederationPlugin. Various release candidate versions of nextjs-mf, node, and utils packages have been published to reflect these changes.
- fix: resolve build hanging issue
- Enable 'named' value for optimization.chunkIds in apply-server-plugins.ts
- Remove redundant comments in apply-server-plugins.ts
- refactor: Improve handling of Next.js and React modules
- Add conditions in apply-server-plugins.ts to handle modules starting with 'react-dom/'
- Include 'react' and 'react-dom' as exact matches in apply-server-plugins.ts
- fix: Resolve build issues at lululemon
- Update import value for 'react/jsx-runtime' in DEFAULT_SHARE_SCOPE in internal.ts
- Update …
> fix: externalization and missing runtime chunks

- packages/node/package.json
This commit adds a new export to package.json for the ./src/ directory. This enables consumers of the package to import individual files from the 'src' directory more easily.
- Add './src/' export to 'exports' object
> fix: Add ./src/ export to package.json

- packages/utilities/src/utils/importRemote.ts
**Description:**
- Unable to use `importRemote` utility for importing root-level modules
**Example:**
```ts
// webpack.config
const moduleFederationConfig = {
....
name: "MyRemoteComps",
exposes: {
".": "src/remotes" // has index.ts that exports all components under the folder
}
}
// at consuming end
const Comp1 = lazy(() =>
importRemote({
url: '<base_url>',
scope: "MyRemoteComps",
module: ".",
}).then(m => m.Comp1)
);
> fix(Utils): Unable to use importRemote util for root exported modules

- packages/nextjs-mf/src/plugins/NextFederationPlugin.ts
I'm not sure whether you'll consider this fix proper, but it works :) 
The basic idea is that some dependency of `nextjs-mf\src\include-defaults.js` requires the package `client-only` causing the error outlined in issue 953, so we don't include the patch file in server side builds. 
Side note I saw your [contributing guideline](https://github.com/module-federation/universe/blob/4216e3d433b585f4952c5da522232a92b207fc1e/CONTRIBUTING.md) and ran `npm run release:next` but for some reason Nx is attempting to version the utils package instead of nextjs-mf, not too familiar with Nx, is there maybe a configuration issue? 
Thanks!
> fix use client issue https://github.com/module-federation/universe/issues/953

- packages/node/README.md
Added more details to the revalidate documentation as the default webpack configuration, which does not hash development chunks, may cause the revalidate method not to work as developers expect.
Motivation: https://github.com/module-federation/universe/issues/843
> doc: Added more details to revalidate documentation

- packages/nextjs-mf/README.md
nextjs-mf documentation is actually broken because of an open `<details>` tag.
Also, a broken link is here for a long time now. I don’t really know which example should be linked, but I think the **nextjs-v13** one is accurate.
> fix(nextjs-mf): update broken documentation

- packages/nextjs-mf/src/plugins/container/InvertedContainerPlugin.ts
Our API Routes using the v7 version of the NextJS MF Plugin are failing with the following error:
```
ERROR    TypeError: Cannot read properties of undefined (reading 'then')
at __webpack_exec__ (/var/task/.next/server/pages/api/config.js:972:60)
```
That happens because the build is including this template:
```
function(moduleId) { return __webpack_require__.own_remote.then(function() { return Promise.all([
Promise.all(__webpack_require__.initRemotes),
Promise.all(__webpack_require__.initConsumes)
]); }).then(function() { return __webpack_exec_proxy__(moduleId); }); }
```
Checking the code, for anything that has `pages/api` (i.e. an API Route) we should not be adding this template, but instead returning the source directly. While investigating why the current check is not passing …
> Fix: v7 API Routes

- packages/typescript/src/lib/TypescriptCompiler.ts
The `replaceAll()` method crashes on Node versions below 15.
fixes https://github.com/module-federation/universe/issues/1177
> fix: Update TypescriptCompiler.ts

- packages/enhanced/.swcrc
- packages/enhanced/src/lib/container/ContainerEntryDependency.ts
- packages/enhanced/src/lib/container/ContainerEntryModule.ts
- packages/enhanced/src/lib/container/ContainerEntryModuleFactory.ts
- packages/enhanced/src/lib/container/ContainerExposedDependency.ts
- packages/enhanced/src/lib/container/ContainerPlugin.ts
- packages/enhanced/src/lib/container/ContainerReferencePlugin.ts
- packages/enhanced/src/lib/container/FallbackDependency.ts
- packages/enhanced/src/lib/container/FallbackItemDependency.ts
- packages/enhanced/src/lib/container/FallbackModule.ts
- packages/enhanced/src/lib/container/FallbackModuleFactory.ts
- packages/enhanced/src/lib/container/ModuleFederationPlugin.ts
- packages/enhanced/src/lib/container/RemoteModule.ts
- packages/enhanced/src/lib/container/RemoteRuntimeModule.ts
- packages/enhanced/src/lib/container/RemoteToExternalDependency.ts
- packages/enhanced/src/lib/sharing/ConsumeSharedFallbackDependency.ts
- packages/enhanced/src/lib/sharing/ConsumeSharedModule.ts
- packages/enhanced/src/lib/sharing/ConsumeSharedPlugin.ts
- packages/enhanced/src/lib/sharing/ConsumeSharedRuntimeModule.ts
- packages/enhanced/src/lib/sharing/ProvideForSharedDependency.ts
- packages/enhanced/src/lib/sharing/ProvideSharedDependency.ts
- packages/enhanced/src/lib/sharing/ProvideSharedModule.ts
- packages/enhanced/src/lib/sharing/ProvideSharedModuleFactory.ts
- packages/enhanced/src/lib/sharing/ProvideSharedPlugin.ts
- packages/enhanced/src/lib/sharing/SharePlugin.ts
- packages/enhanced/src/lib/sharing/ShareRuntimeModule.ts
- packages/enhanced/src/lib/sharing/resolveMatchedConfigs.ts
- packages/enhanced/tsconfig.json
@ScriptedAlchemy - it turns out the import require syntax can be worked around if we use the swc interop helper:
https://swc.rs/docs/configuration/modules#nointerop
We can technically just remove noInterop from .swcrc and it'll work but I made them explicit for now. You can see the difference in the compiled code where they wrap require statements in their wrapper. But this removes the need to import = require().
Tested with start:node and start:next
> Enhanced - remove import require statements for swc interop

- packages/nextjs-mf/src/plugins/NextFederationPlugin/apply-server-plugins.ts
Resolves issues seen in examples repo, where chunks are the same. 
Next no longer uses the main NodeFederationPlugin instance directly. Instead, federation is directly applied via the underlaying plugins
> fix: move cache file hashing to next-mf

- packages/typescript/src/plugins/FederatedTypesPlugin.ts
After installing @module-federation/typescript, I was getting an error that file was not found. In my case this happened because one of the cached files marked for busting was an empty string. This change fixes that by filtering out empty strings for files paths
> fix: filter empty cache files

- packages/typescript/.swcrc
This fixes scenarios where the consuming project does not have @swc/helpers installed. By leaving them external it expects to find them in node_modules, but embedding them at build time is likely the best option.
> Fix: Typescript - make SWC helpers embedded

- .husky/commit-msg
- package.json
* Solution If the husky hook does not take effect, the commit cannot be checked for compliance with the specification
* none
> workflow: optimize husky commit hook

- packages/runtime/src/core.md
- packages/runtime/src/core.ts
- packages/runtime/src/module/index.ts
- packages/runtime/src/plugins/generate-preload-assets.ts
- packages/runtime/src/utils/load.ts
- packages/runtime/src/utils/share.ts
- Features have been added to enhance the functionality of the FederationHost lifecycle hooks, the resolveShare hook in the FederationHost class, the generatePreloadAssets function, and the getRegisteredShare function. 
- A new function, loadScriptNode, has also been added to handle script loading when the document is undefined in node.js environments
- adds types for resolveShare hook
N/A
> feat(runtime): resolveShare runtime hooks

- packages/runtime/project.json
- packages/runtime/vitest.config.ts
before(can not see error infos) :
after:
> fix: vitest not throw error while using @nx/vite:test directly

- .changeset/stale-horses-bathe.md
- .changeset/wet-dancers-raise.md
- packages/enhanced/.eslintrc.json
- packages/enhanced/CHANGELOG.md
- packages/enhanced/package.json
- packages/nextjs-mf/CHANGELOG.md
- packages/nextjs-mf/package.json
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/runtime/CHANGELOG.md
- packages/runtime/package.json
- packages/sdk/CHANGELOG.md
- packages/sdk/package.json
- packages/webpack-bundler-runtime/CHANGELOG.md
- packages/webpack-bundler-runtime/package.json
* feat(runtime): support entry with query by @2heal1 in #1833 
* feat: export sdk simpleJoinRemoteEntry function by @2heal1 in #1858
* fix: vitest not throw error while using @nx/vite:test directly by @2heal1 in #1855 
* chore: Release v0.0.4 by @zhoushaw in #1811 
* chore: remove unused packages by @ScriptedAlchemy in #1825
* chore(deps): update dependency typedoc to v0.25.4 by @renovate in #1805 
* chore(deps): update dependency react-router-dom to v6.21.1 by @renovate in #1846 
* chore(deps): update dependency regenerator-runtime to v0.14.1 by @renovate in #1804 
* chore(deps): update dependency undici to v5.28.2 by @renovate in #1847 
* chore(deps): update dependency core-js to v3.34.0 by @renovate in #1845
Full Changelog: [v0.0.4...v0.0.5](https://github.com/module-federation/universe …
> Release v0.0.5

- .changeset/honest-peas-dress.md
- packages/runtime/src/utils/hooks/pluginSystem.ts
- packages/runtime/src/utils/plugin.ts
rename usePlugins to prevent swc react-refresh from throwing errors when replacing variables
> fix: rename usePlugins to prevent swc react-refresh from throwing errors when replacing variables

- .changeset/quick-chicken-glow.md
- .changeset/wet-pillows-impress.md
- packages/runtime/src/core.ts
- packages/runtime/src/global.ts
- packages/runtime/src/helpers.ts
- packages/runtime/src/module/index.ts
- packages/runtime/src/type/config.ts
- packages/runtime/src/type/plugin.ts
- packages/runtime/src/utils/plugin.ts
* add initContainer and beforeInitContainer hook
* only both version and name matched instance can be re-use
> feat: add init container hook

- packages/enhanced/src/lib/container/ContainerEntryModule.ts
- packages/enhanced/src/lib/container/runtime/FederationRuntimePlugin.ts
- packages/runtime-tools/src/index.ts
- packages/runtime/src/module/index.ts
- packages/runtime/src/type/config.ts
- packages/webpack-bundler-runtime/src/initContainerEntry.ts
- packages/webpack-bundler-runtime/src/types.ts
add remoteEntryInitOptions in container init params
> feat: add remoteEntryInitOptions in container init params

- packages/enhanced/src/declarations/plugins/sharing/ProvideSharedPlugin.d.ts
- packages/enhanced/src/lib/sharing/ProvideSharedDependency.ts
- packages/enhanced/src/lib/sharing/ProvideSharedModule.ts
- packages/enhanced/src/lib/sharing/ProvideSharedModuleFactory.ts
- packages/enhanced/src/lib/sharing/ProvideSharedPlugin.ts
- packages/enhanced/src/lib/sharing/SharePlugin.ts
- packages/enhanced/src/lib/sharing/ShareRuntimeModule.ts
- packages/enhanced/src/schemas/sharing/ProviderSharedPlugin.check.ts
- packages/enhanced/src/schemas/sharing/ProviderSharedPlugin.ts
add shareConfig to ProvideSharePlugin
> feat: add share config

- packages/runtime/rollup.config.js
- packages/runtime/src/core.ts
> chore: update constant

- .changeset/lemon-fans-tickle.md
- packages/enhanced/src/lib/container/runtime/FederationRuntimePlugin.ts
* not duplicate set resolve.alias
In the past, if users set the same alias , it will be overrided by FederationRuntimePlugin .
> fix: not duplicate set resolve.alias

- .changeset/weak-jars-tap.md
- packages/runtime/src/core.ts
window.location.origin will be 'null' in iframe srcDoc
> fix: window.location.origin will be 'null' in iframe srcDoc

- .changeset/shy-spoons-cheer.md
- packages/enhanced/src/lib/container/ModuleFederationPlugin.ts
- packages/enhanced/src/lib/sharing/ConsumeSharedPlugin.ts
- packages/runtime/src/utils/share.ts
- packages/webpack-bundler-runtime/src/initContainerEntry.ts
* fix: remove duplicate init shareScopeMap
* fix: normalize schemas path
* fix: shared is loaded if it has lib attr
> fix: webpackRequire.S has been attached with instance.shareScopeMap

- .changeset/lemon-fans-tickle.md
- .changeset/long-bulldogs-reply.md
- .changeset/shy-spoons-cheer.md
- .changeset/weak-jars-tap.md
- packages/enhanced/CHANGELOG.md
- packages/enhanced/package.json
- packages/nextjs-mf/CHANGELOG.md
- packages/nextjs-mf/package.json
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/runtime-tools/CHANGELOG.md
- packages/runtime-tools/package.json
- packages/runtime/CHANGELOG.md
- packages/runtime/package.json
- packages/sdk/CHANGELOG.md
- packages/sdk/package.json
- packages/webpack-bundler-runtime/CHANGELOG.md
- packages/webpack-bundler-runtime/package.json
* fix(nextjs-mf): production build issues during next compile by @ScriptedAlchemy in https://github.com/module-federation/universe/pull/1940
* fix: copy decalaration files to output by @2heal1 in https://github.com/module-federation/universe/pull/1957
* fix: not duplicate set resolve.alias by @2heal1 in https://github.com/module-federation/universe/pull/1948
* fix: window.location.origin will be 'null' in iframe srcDoc by @2heal1 in https://github.com/module-federation/universe/pull/1956
* fix: webpackRequire.S has been attached with instance.shareScopeMap by @2heal1 in https://github.com/module-federation/universe/pull/1962
* docs: added contribution guidelines on how to publish official versions by @zhoushaw in https://github.com/module-federation/universe/pull/1944
* Release v0.0.8 by …
> Release v0.0.9

- .github/workflows/build-and-test.yml
- apps/3000-home/cypress/e2e/app.cy.ts
- apps/3001-shop/cypress/e2e/app.cy.ts
- apps/3002-checkout/cypress/e2e/app.cy.ts
The navigation tests seem to be flakey in dev server mode on CI. I will investigate in the future to run prod build and test against that.
for now i will disable it
> chore: disable unreliable e2e of next project

- packages/enhanced/package.json
- packages/enhanced/src/lib/container/ContainerReferencePlugin.ts
- packages/enhanced/src/lib/container/runtime/utils.ts
- packages/enhanced/test/ConfigTestCases.template.js
- packages/enhanced/test/configCases/container/comonjs-runtime-plugins/App.js
- packages/enhanced/test/configCases/container/comonjs-runtime-plugins/ComponentA.js
- packages/enhanced/test/configCases/container/comonjs-runtime-plugins/index.js
- packages/enhanced/test/configCases/container/comonjs-runtime-plugins/node_modules/react.js
- packages/enhanced/test/configCases/container/comonjs-runtime-plugins/runtimePlugin.js
- packages/enhanced/test/configCases/container/comonjs-runtime-plugins/test.config.js
- packages/enhanced/test/configCases/container/comonjs-runtime-plugins/upgrade-react.js
- packages/enhanced/test/configCases/container/comonjs-runtime-plugins/webpack.config.js
- packages/enhanced/test/configCases/sharing/consume-multiple-versions/index.js
- packages/runtime/README.md
- packages/runtime/src/utils/load.ts
- packages/sdk/src/node.ts
- packages/sdk/src/types/stats.ts
- packages/webpack-bundler-runtime/src/constant.ts
- packages/webpack-bundler-runtime/src/remotes.ts
- pnpm-lock.yaml
> feat: support cjs

- .changeset/fast-sheep-melt.md
- packages/runtime/src/core.ts
Allows export proxies and wrappers around the module that is loaded. 
This enables things like SSR, where we can track function invocation not chunk load to register args.id from the onload hook. 
This allows us to return preload scripts in DOM with server rendering etc.  
Allows wrapping in error boundaries or adapters 
https://github.com/module-federation/universe/pull/1985
https://github.com/module-federation/universe/issues/1984
the terminal is displaying logs in repetition for each time it is executed again.  Able to intercept exports function calls
> feat(runtime): allow onload hook to return wrapped module

- .changeset/curly-mangos-worry.md
- .changeset/fast-sheep-melt.md
- .changeset/metal-walls-drop.md
- .changeset/modern-snails-chew.md
- .changeset/odd-tomatoes-fetch.md
- .changeset/popular-spoons-grin.md
- packages/enhanced/CHANGELOG.md
- packages/enhanced/package.json
- packages/nextjs-mf/CHANGELOG.md
- packages/nextjs-mf/package.json
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/runtime-tools/CHANGELOG.md
- packages/runtime-tools/package.json
- packages/runtime/CHANGELOG.md
- packages/runtime/package.json
- packages/sdk/CHANGELOG.md
- packages/sdk/package.json
- packages/webpack-bundler-runtime/CHANGELOG.md
- packages/webpack-bundler-runtime/package.json
* feat(runtime): allow onload hook to return wrapped module by @ScriptedAlchemy in https://github.com/module-federation/universe/pull/1987
* feat(runtime): automatically complete the snapshot so that devtool can visualize it by @zhoushaw in https://github.com/module-federation/universe/pull/1982
* fix(enhanced): async boundary on dependOn named chunks by @ScriptedAlchemy in https://github.com/module-federation/universe/pull/1960
* fix(nextjs-mf): remove delegate code by @ScriptedAlchemy in https://github.com/module-federation/universe/pull/1938
* fix(node): Improve chunk flushing by @ScriptedAlchemy in https://github.com/module-federation/universe/pull/1985
* Release v0.0.9 by @zhoushaw in https://github.com/module-federation/universe/pull/1965
* chore: disable unreliable e2e of next …
> Release v0.0.10

- packages/runtime/__tests__/preload-remote.spec.ts
- packages/runtime/src/global.ts
Prevent runtime error when unsafe-eval is restricted by policy
Webpack may transform globalThis into require.g, but that will be something the end user must manage if they cannot support unsafe-eval policy on runtime scripts. 
Try to use new function and catch and return whatever globalThis is 
#2015
> fix(runtime): support restricted unsafe-eval environments

- apps/3000-home/next.config.js
- apps/3000-home/pages/index.tsx
- apps/3001-shop/next.config.js
- apps/3002-checkout/next.config.js
Added a trailing slash to the shared config on the examples from `3000-home`, `3001-shop`, and `3002-checkout` that were using the Next.js plugin.
The slash is needed for them to be properly shared since it will cause webpack to partially match the [optimization](https://nextjs.org/docs/app/api-reference/next-config-js/optimizePackageImports) of the imports that Next.js started doing since 13.5 to some packages.
This should solve https://github.com/module-federation/universe/issues/2037.
> fix(3000-home): add trailing slash on antd and lodash shared config

- .changeset/weak-baboons-think.md
- packages/nextjs-mf/src/plugins/NextFederationPlugin/index.ts
The `errorLoadRemote` hook was being overridden by the default `runtimePlugin` definition from within the `nextjs-mf` plugin.
This changes the order of the definition to take in the user-provided plugin lastly so it overrides the default.
This should solve https://github.com/module-federation/universe/issues/2039.
> fix(nextjs-mf): change runtimePlugin definition order 

- .changeset/fresh-baboons-train.md
- packages/runtime/__tests__/preload-remote.spec.ts
- packages/runtime/src/global.ts
> fix(runtime): nativeGlobal is undefined

- .changeset/hip-cars-drop.md
- packages/runtime/src/core.ts
- packages/runtime/src/module/index.ts
- packages/runtime/src/type/config.ts
fix(runtime): runtime should not pre-register shared while strategy is 'loaded-first'
> fix(runtime): runtime should not pre-register shared while strategy is 'loaded-first'

- .changeset/fresh-baboons-train.md
- .changeset/hip-cars-drop.md
- .changeset/soft-days-chew.md
- .changeset/weak-baboons-think.md
- packages/enhanced/CHANGELOG.md
- packages/enhanced/package.json
- packages/nextjs-mf/CHANGELOG.md
- packages/nextjs-mf/package.json
- packages/node/CHANGELOG.md
- packages/node/package.json
- packages/runtime-tools/CHANGELOG.md
- packages/runtime-tools/package.json
- packages/runtime/CHANGELOG.md
- packages/runtime/package.json
- packages/sdk/CHANGELOG.md
- packages/sdk/package.json
- packages/webpack-bundler-runtime/CHANGELOG.md
- packages/webpack-bundler-runtime/package.json
* fix(runtime): support restricted unsafe-eval environments by @ScriptedAlchemy in https://github.com/module-federation/universe/pull/2018
* fix(3000-home): add trailing slash on antd and lodash shared config by @ryok90 in https://github.com/module-federation/universe/pull/2038
* fix(nextjs-mf): change runtimePlugin definition order  by @ryok90 in https://github.com/module-federation/universe/pull/2052
* fix: normalize bundler runtime import paths by @jonthomp in https://github.com/module-federation/universe/pull/1997
* fix(runtime): nativeGlobal is undefined by @2heal1 in https://github.com/module-federation/universe/pull/2058
* fix(runtime): runtime should not pre-register shared while strategy is 'loaded-first' by @2heal1 in https://github.com/module-federation/universe/pull/2056
* …
> Release v0.0.11

- .changeset/forty-dolls-dance.md
- packages/runtime/__tests__/__snapshots__/preload-remote.spec.ts.snap
- packages/runtime/__tests__/preload-remote.spec.ts
- packages/runtime/src/core.ts
- packages/runtime/src/utils/preload.ts
- packages/sdk/src/dom.ts
* use link to preload js assets
* add createLink hook
> fix(runtime): use link to preload js assets

- .changeset/giant-pears-admire.md
- package.json
- packages/native-federation-tests/package.json
- packages/native-federation-tests/src/index.test.ts
- packages/native-federation-tests/src/index.ts
- packages/native-federation-typescript/package.json
- packages/native-federation-typescript/src/index.test.ts
- packages/native-federation-typescript/src/index.ts
- pnpm-lock.yaml
During vite dev mode, `writeBundle` hook is not invoked.
Said so, types and tests are not re-generated while developing
> fix: native federation behaviour on vite

- .changeset/fast-games-report.md
- packages/nextjs-mf/src/plugins/container/runtimePlugin.ts
Runtime plugin causes false failure when returning static exports object
> fix(nextjs-mf): only call module factory in valid conditions

- .changeset/thick-birds-clap.md
- apps/3001-shop/pages/shop/index.tsx
- apps/3002-checkout/pages/checkout/index.tsx
- packages/nextjs-mf/src/plugins/container/runtimePlugin.ts
automatically cache bust remote entry injection
https://github.com/module-federation/universe/issues/2208
> fix(nextjs-mf): cache bust remote urls

- .changeset/great-radios-check.md
- packages/nextjs-mf/README.md
- packages/nextjs-mf/utils/index.ts
deprecate use of utilities package
> fix(nextjs-mf): deprecate utils use

- packages/enhanced/src/lib/container/ContainerEntryModule.ts
- packages/enhanced/src/lib/container/ContainerPlugin.ts
- packages/nextjs-mf/README.md
remove additional entry module injections into federation, instead it will use the runtime module for eager loading of runtime and plugin entry modules
> refactor(enhanced): no additional entry dependency

- .changeset/light-tomatoes-camp.md
- packages/nextjs-mf/src/plugins/NextFederationPlugin/index.ts
- packages/utilities/src/types/index.ts
disable noop exposes of next modules when skip share is enabled
> fix(nextjs-mf): skip share next internals

- apps/website-new/docs/en/guide/basic/chrome-devtool.mdx
* docs: fix devtool doc format error
none
> docs: fix devtool doc format error

- .changeset/dry-walls-enjoy.md
- apps/website-new/docs/en/configure/dts.mdx
- apps/website-new/docs/zh/configure/dts.mdx
- packages/dts-plugin/src/plugins/DevPlugin.ts
- packages/dts-plugin/src/plugins/GenerateTypesPlugin.ts
- packages/dts-plugin/src/plugins/TypesPlugin.ts
- packages/enhanced/src/schemas/container/ModuleFederationPlugin.ts
- packages/sdk/src/types/plugins/ModuleFederationPlugin.ts
detect whether the project is ts, if no ,disable dts plugin automatic . 
It also add `dts.tsconfigPath` field
> fix: detect whether the project is ts

- .changeset/stale-hairs-remain.md
- apps/react-ts-nested-remote/project.json
- apps/runtime-demo/3006-runtime-remote/project.json
- packages/dts-plugin/src/core/lib/DTSManager.ts
- packages/dts-plugin/src/core/lib/archiveHandler.ts
output error in file: when consumer starts and provider not start , it will output too many useless error , so it will be output in file.
> fix: output error in file

- .changeset/angry-ways-return.md
- packages/runtime/__tests__/share.ts
- packages/runtime/__tests__/shares.spec.ts
- packages/runtime/src/type/config.ts
- packages/runtime/src/utils/share.ts
in build config , it supports `import:false` , and the runtime need support the config as well. 
**build config** 
```js
new ModuleFederationPlugin({
shared: {
'react': { 
// just use host react
import: false,
requiredVersion: '^16.0.0'
}
}
})
```
and it equals the below runtime config
```js
import { init } from '@module-federation/runtime';
init({
shared: {
react: {
scope: ['default'],
// no need to set lib or get
shareConfig: {
singleton: true,
requiredVersion: '^16.0.0',
eager: false,
},
}
}
})
```
> feat: align with shared import:false

- .changeset/green-news-leave.md
- packages/enhanced/src/lib/container/runtime/FederationRuntimeModule.ts
- packages/enhanced/src/lib/container/runtime/getFederationGlobal.ts
Add ensureChunk JS matcher function to accessable location at runtime
This allows us to add custom runtime plugins like node federation which replace or add to require.f but to do so we need to know what is a real JS chunk to match on. 
exampe:
```js
// Dynamic filesystem chunk loading for javascript
if (__webpack_require__.f) {
const handle = function (chunkId, promises) {
var installedChunkData = installedChunks[chunkId];
if (installedChunkData !== 0) {
// 0 means "already installed".
if (installedChunkData) {
promises.push(installedChunkData[2]);
} else {
// here is matcher
const matcher = __webpack_require__.federation.chunkMatcher
? __webpack_require__.federation.chunkMatcher(chunkId)
: true;
if (matcher) {
```
> feat(enhanced): chunk matcher to federation runtime

- .changeset/pink-bulldogs-laugh.md
- .github/workflows/build-and-test.yml
- packages/enhanced/src/lib/container/AsyncBoundaryPlugin.ts
Improve async boundary for split chunk rules and cases where dependOn is used on entrypoints
Should search deep in chunks for remote modules and should collect all initial chunks needed for boundary
> feat(enhanced): improve async boundary for sibling chunk dep

- packages/native-federation-tests/src/index.ts
- packages/native-federation-typescript/package.json
- packages/native-federation-typescript/src/index.test.ts
- packages/native-federation-typescript/src/index.ts
- packages/native-federation-typescript/src/lib/writeBundle/host.ts
- packages/native-federation-typescript/src/lib/writeBundle/remote.ts
- pnpm-lock.yaml
According to the previous PRs made by @2heal1, I think that there's no need to build custom classes to manage rpc in order to speed up things.
Instantiation an additional process each time that types are compiled/downloaded can be costly: using piscina, which wraps worker threads, can help us achieving the same result with a more concise code.
Of course, if the methodology is approved, I'm going to implement it for native-federation-tests as well
> feat(native-federation-typescript): speedup

- .changeset/tasty-parents-guess.md
- packages/runtime/__tests__/global.spec.ts
- packages/runtime/src/index.ts
(runtime) global loadRemote doesn't support generic (ts fails)
So I've added support for:
- loadShare
- loadShareSync
- loadRemote
#2325
> fix(runtime): preserve generic in loadRemote/loadShare/loadShareSync (#2325)

- .changeset/gorgeous-boats-grab.md
- packages/nextjs-mf/src/plugins/NextFederationPlugin/apply-client-plugins.ts
- packages/nextjs-mf/src/plugins/NextFederationPlugin/index.ts
- Allow `publicPath` to be modified for the client side.
- Fixed the typing for the ModuleFederationPlugin base options for the NextFederationPlugin.
- Specified manifest export directory to fit Next.js client static folder.
[[nextjs-mf] Manifest is not being generated for the client](https://github.com/module-federation/universe/issues/2294)
> fix(nextjs-mf): enable manifest generation on clientside when setting publicPath

- apps/website-new/docs/en/guide/start/quick-start.mdx
> chore: remove duplicated section from quick-start docs

- .changeset/two-files-jog.md
- packages/dts-plugin/tsup.config.ts
- packages/native-federation-tests/tsup.config.ts
- packages/native-federation-typescript/tsup.config.ts
- packages/third-party-dts-extractor/tsup.config.ts
To enable testing also on windows in the future, it would be better to not hardcode path separator
> fix: tsup config join

- .changeset/quick-dodos-tie.md
- packages/manifest/src/StatsManager.ts
remoteEntry chunk may have css files which need to be exclude
> fix: remoteEntry chunk may have css files which need to be exclude

- .changeset/plenty-shoes-grab.md
- apps/website-new/docs/en/guide/framework/nextjs.mdx
- apps/website-new/docs/en/practice/frameworks/next/presets.mdx
- apps/website-new/docs/zh/guide/framework/nextjs.mdx
- apps/website-new/docs/zh/practice/frameworks/next/presets.mdx
- packages/nextjs-mf/README.md
- packages/nextjs-mf/src/internal.ts
Sets `requiredVersion` to `false` in the default share scope.  This fixes a warning I've been seeing in my project with `react.jsx-runtime`
> shared module react/jsx-runtime
> No required version specified and unable to automatically determine one. Unable to find required version for "react" in description file (...)
I believe this setting should match the config in the `react` share scope?
I've also synced the readme/docs share scope snippet.
> fix(nextjs-mf): fix react/jsx-runtime required version warning

- .changeset/funny-parents-sneeze.md
- packages/node/src/runtimePlugin.ts
fixing bad var in error callback of runtime plugin
> fix(node): missing variable in runtime plugin error call

- apps/website-new/docs/en/configure/index.mdx
`ModuleFederationOptions` had a typo in the `exposes` property name
> docs: fixes parameter name typo

- .changeset/unlucky-teachers-yawn.md
- packages/sdk/src/dom.ts
fix(runtime): resolve the problem that static resource preload is not reused
> fix(runtime): resolve the problem that static resource preload is not reused

- .changeset/popular-fishes-speak.md
- packages/runtime/src/remote/index.ts
fix: only delete can be configurable descriptor
#2436
> fix: only delete can be configurable descriptor

- .changeset/large-suits-sit.md
- packages/enhanced/src/lib/container/ModuleFederationPlugin.ts
- packages/enhanced/test/setupTestFramework.js
- packages/managers/__tests__/SharedManager.spec.ts
- packages/managers/src/SharedManager.ts
support normalize shared.import option
> chore: support normalize shared.import option

- apps/website-new/docs/en/configure/shared.mdx
- apps/website-new/docs/zh/configure/shared.mdx
> docs: add shared.shareScope

- .changeset/perfect-camels-type.md
- .changeset/wet-geckos-tan.md
- .github/workflows/build-and-test.yml
- apps/runtime-demo/3006-runtime-remote/src/components/WebpackPng.tsx
- apps/runtime-demo/3006-runtime-remote/src/components/a.css
- packages/chrome-devtools/src/utils/chrome/fast-refresh.ts
- packages/runtime/__tests__/__snapshots__/preload-remote.spec.ts.snap
- packages/runtime/src/plugins/snapshot/index.ts
- packages/runtime/src/utils/preload.ts
- packages/sdk/__tests__/dom.spec.ts
- packages/sdk/src/dom.ts
* fix: devtools Adjustments hmr changes the behavior of shared to make changes more stable
* fix: In load remote, link preload is not used to preload resources, preventing resource reloading
#2569
> fix: fixed preload resource reuse issues and devtool hmr shared

- .changeset/sharp-dryers-sparkle.md
- .github/workflows/build-and-test.yml
- packages/enhanced/src/lib/container/AsyncBoundaryPlugin.ts
- packages/nextjs-mf/src/plugins/container/InvertedContainerRuntimeModule.ts
If a specific runtime chunk does not implement federation and async boundary is used on the build, it will crash that runtime
https://github.com/module-federation/core/issues/2559
> fix(nextjs-mf): Do not attach runtime to api runtime chunks

- .changeset/silver-dolphins-relate.md
- packages/runtime/src/core.ts
- packages/runtime/src/module/index.ts
- packages/runtime/src/shared/index.ts
- packages/runtime/src/type/config.ts
- packages/webpack-bundler-runtime/src/initContainerEntry.ts
pass shareScopeMap to container which allow remote sync host's all shareScope 
users can write runtime plugin to sync multiple shareScope 
```js
function multipleShareScopePlugin() {
return {
name: "multiple-share-scope",
initContainerShareScopeMap(args) {
try {
const { hostShareScopeMap, origin, scopeName } = args;
if (hostShareScopeMap) {
Object.keys(hostShareScopeMap).forEach((hostShareScopeName) => {
if (hostShareScopeName === scopeName) {
return;
}
const hostShareScope = hostShareScopeMap[hostShareScopeName];
origin.shareScopeMap[hostShareScopeName] = hostShareScope;
});
}
} catch (err) {
console.error(new Error(err));
}
return args;
}
};
}
```
> feat: support pass shareScopeMap

- .changeset/strange-bottles-confess.md
- packages/sdk/__tests__/dom.spec.ts
- packages/sdk/src/dom.ts
fix(sdk): the returned properties are used by default when create script and create link hook
> fix(sdk): the returned properties are used by default when create script and create link hook

- .changeset/clean-wombats-kiss.md
- packages/dts-plugin/src/core/lib/DTSManager.ts
- packages/dts-plugin/src/core/lib/archiveHandler.test.ts
- packages/dts-plugin/src/core/lib/archiveHandler.ts
- packages/dts-plugin/src/core/lib/utils.spec.ts
- packages/dts-plugin/src/core/lib/utils.ts
when fetch dts file/zip , use ipv4 first
> fix: use ipv4 first while load local remote

- .changeset/nine-queens-ring.md
- packages/dts-plugin/src/core/lib/DTSManager.ts
- packages/dts-plugin/src/core/lib/typeScriptCompiler.ts
fix(dts-plugin): replace sourceEntry with index if the value is '.'
if expose key is `.` , the dts filename will be `.d.ts` , and it can not referenced correctly
> fix(dts-plugin): replace sourceEntry with index if the value is '.'

- .changeset/dull-berries-judge.md
- packages/dts-plugin/src/core/configurations/hostPlugin.ts
- packages/sdk/src/constant.ts
- packages/webpack-bundler-runtime/src/constant.ts
- packages/webpack-bundler-runtime/src/remotes.ts
if remote name start with `ENCODE_NAME_PREFIX` , it will be decoded. 
This feature is used to support remote name which has `@` and other characters which can not be used in var `globalObject` , and the name have to transformed. 
take examples:
```js
new ModuleFederationPlugin({
name:'@scope/button'
});
encodeName('@scope/button',ENCODE_NAME_PREFIX) === 'ENCODE_NAME_PREFIXscope_scope__button'
```
> feat(dts-plugin): decode encoded remote name

- .changeset/mighty-goats-hang.md
- packages/dts-plugin/src/core/lib/DTSManager.spec.ts
- packages/dts-plugin/src/core/lib/DTSManager.ts
- packages/dts-plugin/src/core/lib/archiveHandler.ts
- packages/dts-plugin/vite.config.ts
no delete exist types if fetch new types failed
#2489
> fix: no delete exist types if fetch new types failed

- .changeset/cuddly-cougars-deny.md
- packages/dts-plugin/src/core/lib/DtsWorker.ts
check pid is undefined before kill it
> fix: check pid is undefined before kill it

- .changeset/nervous-cougars-switch.md
- packages/dts-plugin/src/core/lib/DTSManager.ts
download api types when types refresh
> fix: download api types when types refresh

- .changeset/young-books-carry.md
- packages/manifest/src/StatsManager.ts
- packages/manifest/src/utils.ts
…xtra file
In some cases, manifest collect extra file, when preloadRemote is called, there will cause extra consuption
> fix: fix expose collect assets do not filter entry point cause load extra file

- apps/website-new/docs/en/practice/bridge/vue-bridge.mdx
The PackageManagerTabs component is mission from the vue bridge page.
> fix(docs): missing PackageManagerTabs import

- .changeset/green-chefs-crash.md
- apps/runtime-demo/3005-runtime-host/webpack.config.js
- packages/enhanced/src/lib/container/runtime/utils.ts
Skip record remotes while the entry is legacy.
ModuleFederationV2 runtime only support `script` format entry , so it will ignore others entry. 
The other format entry will be loaded as MFV1 way.
#2740
> fix: skip record remotes while the entry is legacy

- .changeset/clean-kiwis-repair.md
- packages/dts-plugin/src/core/configurations/hostPlugin.test.ts
- packages/dts-plugin/src/core/configurations/remotePlugin.test.ts
- packages/dts-plugin/src/core/configurations/remotePlugin.ts
- packages/dts-plugin/src/core/lib/DTSManager.advance.spec.ts
- packages/dts-plugin/src/core/lib/DTSManager.spec.ts
- packages/dts-plugin/src/core/lib/DtsWorker.spec.ts
- packages/dts-plugin/src/core/lib/archiveHandler.test.ts
- packages/dts-plugin/src/core/lib/typeScriptCompiler.test.ts
- packages/dts-plugin/src/core/lib/typeScriptCompiler.ts
- packages/dts-plugin/tests/setup.ts
- packages/dts-plugin/tests/vue-tsc2/index.spec.ts
- packages/dts-plugin/vite.config.ts
* delete temp tsConfig.compilerOptions.paths 
* add extends which value is original tsConfig.json
> fix(dts-plugin): temp tsconfig path should extends original tsconfig

- .changeset/little-snakes-fail.md
- packages/dts-plugin/tests/setup.ts
- packages/dts-plugin/vite.config.ts
- packages/third-party-dts-extractor/src/ThirdPartyExtractor.ts
no collect node internal utils
> fix: no collect node internal utils

- apps/modernjs-ssr/dynamic-nested-remote/tsconfig.json
- packages/modernjs/src/cli/configPlugin.ts
- packages/modernjs/src/cli/ssrPlugin.ts
- packages/modernjs/src/cli/utils.spec.ts
- packages/modernjs/src/cli/utils.ts
- packages/node/global.d.ts
- packages/node/package.json
- packages/node/src/index.ts
- packages/node/src/plugins/UniverseEntryChunkTrackerPlugin.ts
- pnpm-lock.yaml
* add UniverseEntryChunkTrackerPlugin to support both webpack and rspack live reload
* only webpack need to add watchOptions.ignored to avoid i infinite refresh
> fix: support rspack ssr live reload

- .changeset/good-shirts-cover.md
- packages/runtime/src/utils/preload.ts
In NextJS, with a recent update to the nextjs-mf plugin, the app will immediately crash in the browser with "TypeError: Cannot convert undefined or null to object" because the `attrs` object is undefined in the next-internal-plugin createScript hook. It looks like there were a couple of places where only `url` was passed to the hook, and in those cases the runtime plugin bundled with nextjs-mf would fail when createScript was emitted.
The error appears only to surface when using the manifest in NextJS, but I think the underlying issue is that `attrs` is expected by the hook but it isn't present when preloading.
Steps to reproduce:
1. Checkout the `nextjs-ssr-manifest` example from this PR: https://github.com/module-federation/module-federation-examples/pull/4231
2. Update the …
> fix(runtime): ensured attributes are forwarded to createScript hook

- .changeset/large-bikes-fail.md
- packages/utilities/package.json
This PR modifies the package.json to expose the ESM files from the "utilities" package, using similar patterns as the "runtime" package. This change will help Webpack perform tree-shaking more effectively.
The import:
```js
import { importRemote as importRemoteUtility } from '@module-federation/utilities';
```
See numbers in the following images:
**Before**
**After**
> feat(utilities): expose esm from package json

- .changeset/fifty-beans-jog.md
- packages/enhanced/src/wrapper/ModuleFederationPlugin.ts
correct enhanced ModuleFederation types error
before: 
after: 
#2802
> fix(enhanced): correct enhanced ModuleFederation types error

- .changeset/friendly-pans-clean.md
- packages/enhanced/src/index.ts
remove useless but has side effect export.
`lib/sharing/utils` will require `webpack/lib/util/fs`, but `process.env['FEDERATION_WEBPACK_PATH']` only be injected after `ModuleFederationPlugin.apply` be called . 
And the utils seems not be used anymore, so it can be removed
> fix(enhanced): remove useless but has side effect export

- .changeset/giant-fishes-itch.md
- packages/runtime/src/type/config.ts
- packages/runtime/src/utils/share.ts
- Provide users an option to mark modules in the shared scope as loaded.
- #2789
> feat(runtime): provide users to mark share dependency as loaded #2789

- .changeset/itchy-mayflies-destroy.md
- .changeset/thin-ducks-share.md
- packages/runtime/src/core.ts
- packages/runtime/src/utils/preload.ts
- packages/sdk/__tests__/dom.spec.ts
- packages/sdk/src/dom.ts
* no add default attrs to the element which is provided by users
If user sets `createLink` or `createScript` hook , and return the element , it will be added the default attrs ,like `crossorigin` which may cause preload failed 
So it should not add default attrs if users return the element , and just use the users element direcyly.
* add attrs option to createLink hook , which can help users remain previous behavior
> fix: no add default attrs to the element which is provided by users

- .changeset/itchy-ducks-crash.md
- packages/runtime/src/core.ts
- packages/runtime/src/remote/index.ts
- packages/runtime/src/shared/index.ts
- packages/runtime/src/type/config.ts
- packages/webpack-bundler-runtime/src/initializeSharing.ts
handle circular init shared
https://github.com/idonava/base-mf-app/issues/2
> fix: handle circular init shared

- packages/rspack/src/ModuleFederationPlugin.ts
Currently, when using `@module-federation/rspack/ModuleFederationPlugin` (e.g. via `@module-federation/enhanced/rspack`, the DtsPlugin is still being instantiated regardless of whether `options.dts = false`.
This aligns the behaviour with `@module-federation/enhanced/webpack`
> fix(rspack): do not instantiate DtsPlugin when options.dts = false

- apps/3000-home/cypress/e2e/app.cy.ts
- apps/manifest-demo/webpack-host/webpack.config.js
- apps/runtime-demo/3005-runtime-host/project.json
- apps/runtime-demo/3005-runtime-host/webpack.config.js
- apps/runtime-demo/3006-runtime-remote/project.json
- apps/runtime-demo/3006-runtime-remote/src/components/a.css
- apps/runtime-demo/3006-runtime-remote/webpack.config.js
- apps/runtime-demo/3007-runtime-remote/project.json
- apps/runtime-demo/3007-runtime-remote/webpack.config.js
- apps/runtime-demo/3008-runtime-remote/project.json
Resolve some build config issues
> chore: fix build issues and deps

- .github/workflows/devtools.yml
- package.json
- packages/enhanced/src/lib/container/HoistContainerReferencesPlugin.ts
- packages/enhanced/src/lib/container/runtime/FederationRuntimePlugin.ts
Export getAllReferencedModules as a utility and not a class method
> refactor(enhanced): export getAllReferencedModules as a util

- .changeset/grumpy-lobsters-boil.md
- packages/modernjs/src/cli/utils.ts
correct splitChunks.cacheGroups key which need to be removed
* `lib-react` => `react`
* `lib-router` => `router`
#2933
> fix(modernjs): correct splitChunks.cacheGroups key which need to be removed

- .changeset/nice-crews-beg.md
- packages/modernjs/src/cli/configPlugin.ts
- packages/modernjs/src/cli/ssrPlugin.ts
auto set enableAsyncEntry when bundler is rspack
#2933
> fix(modernjs): auto set enableAsyncEntry when bundler is rspack

- .changeset/rude-trees-ring.md
- packages/runtime/__tests__/shares.spec.ts
- packages/runtime/src/shared/index.ts
- packages/sdk/src/types/plugins/ModuleFederationPlugin.ts
- packages/storybook-addon/src/lib/storybook-addon.ts
set loading if registeredShared not set
> fix(runtime): set loading if registeredShared not set

- .changeset/fast-cherries-itch.md
- packages/modernjs/src/cli/configPlugin.ts
mfConfigPlugin should run after @modern-js/plugin-initialize
@modern-js/plugin-initialize will inject bundlerType , so we must run our plugin after the initialize plugin has executed
https://github.com/web-infra-dev/modern.js/blob/main/packages/solutions/app-tools/src/plugins/initialize/index.ts#L44
> fix(modernjs): mfConfigPlugin should run after modernjs initial plugin

- .changeset/fifty-kangaroos-compete.md
- packages/bridge/bridge-react-webpack-plugin/src/utis.ts
feat: adjust bridge router alias strategy to alias to router-v6 when not found react-router-dom in package.json.
> feat: adjust bridge router alias strategy

- .changeset/kind-cups-stare.md
- packages/dts-plugin/src/core/lib/utils.ts
- packages/manifest/src/utils.ts
zipName should add prefix if remoteEntry has it
#2949
> fix(dts-plugin): zipName should add prefix if remoteEntry has it

- .github/workflows/e2e-modern.yml
- apps/manifest-demo/3010-rspack-provider/tsconfig.app.json
- apps/manifest-demo/3010-rspack-provider/tsconfig.json
- packages/data-prefetch/rollup.config.js
1. update 3010-rspack-provider tsConfig.json which should include .css declaration
2. remove data-prefetc rollup external option , using auto-external instead .
> fix: upgrade nx ci error

- packages/dts-plugin/src/core/lib/typeScriptCompiler.ts
In `/packages/dts-plugin/src/core/lib/typeScriptCompiler.ts:89`, the regex already removes the `.d.ts` extension, so the expose path can be correctly mapped to an entry. Calling removeExt was further processing paths like `foo.component` to just `foo`, resulting in `undefined` being returned in `getExposeKey`.
I didn't check the testing checkbox because I encountered issues with some tests even before making the changes. I hope that, even if this PR doesn't meet the criteria for merging, it can at least serve as documentation for someone else to fix it.
https://github.com/module-federation/core/issues/2957
> fix(dts-plugin): support exposes files with multiple dots in names

- packages/nextjs-mf/src/plugins/NextFederationPlugin/index.ts
use add include instead of noop to expose
> fix(nextjs-mf): use addInclude to ensure defaults are consumed somewhere

- .changeset/nervous-tomatoes-raise.md
- packages/runtime/src/remote/index.ts
- packages/runtime/src/shared/index.ts
catch init remote error in errorLoadRemote hook
> fix(runtime): catch init remote error in errorLoadRemote hook

- apps/website-new/docs/en/plugin/dev/index.mdx
- apps/website-new/docs/zh/plugin/dev/index.mdx
- packages/runtime/__tests__/hooks.spec.ts
- packages/runtime/src/utils/load.ts
`loadEntry hook` returns the unprocessed module according to the original logic, and the current situation will report an error
``` js
{
name: "loadEntryPlugin",
loadEntry({remoteInfo}) {
if (remoteInfo.name === "test") {
return {init, get}
}
// other module error
}
}
```
> fix(runtime): hooks loadEntry default behavior

- apps/website-new/docs/en/configure/index.mdx
- apps/website-new/docs/en/guide/basic/_meta.json
- apps/website-new/docs/en/guide/basic/vite.mdx
- apps/website-new/docs/zh/guide/basic/_meta.json
- apps/website-new/docs/zh/guide/basic/vite.mdx
> feat(vite): Compatibility documentation

- .changeset/hip-pandas-care.md
- packages/nextjs-mf/src/plugins/container/runtimePlugin.ts
Prevents a failure on parsing the Next.js script runtime when the browser has a strict CSP policy and 'unsafe-eval' is not enabled.
Note: I saw other parts of the codebase using similar code, but some of these places might execute only on the server (eg. the node plugin), I decided to just scope my changes to the Next.js plugin for now.
https://github.com/module-federation/core/issues/2759
> Make the Next.js plugin work with strict CSP settings

- apps/website-new/docs/en/_meta.json
- apps/website-new/docs/en/guide/start/quick-start.mdx
- apps/website-new/docs/en/practice/frameworks/angular/_meta.json
- apps/website-new/docs/en/practice/frameworks/angular/using-nx-for-angular.mdx
- apps/website-new/docs/en/practice/frameworks/react/_meta.json
- apps/website-new/docs/en/practice/frameworks/react/using-nx-for-react.mdx
Add Nx Practice Sections to the React + Angular Framework sections.
1. Add Nx to Ecosystem dropdown
2. Add Nx Angular Practice Guide
3. Add Nx React Practice Guide
4. Add Nx Callout on Quick Start Guide
> docs(website-new): add nx guides

- apps/router-demo/router-host-2000/package.json
- apps/router-demo/router-host-v5-2200/package.json
- apps/router-demo/router-host-vue3-2100/package.json
- apps/router-demo/router-remote1-2001/package.json
- apps/router-demo/router-remote2-2002/package.json
- apps/router-demo/router-remote3-2003/package.json
- apps/router-demo/router-remote4-2004/package.json
- packages/rsbuild-plugin/package.json
- packages/rsbuild-plugin/src/cli/index.ts
- pnpm-lock.yaml
Fix failed to load MF remote modules when using `server.base`.
The default `dev.assetPrefix` is set to the value of `server.base`, and Rsbuild should replace it with `dev.assetPrefix: true` to ensure that the remote module's assets can be requested by consumer apps with the correct URL.
- resolve https://github.com/web-infra-dev/rsbuild/issues/3780
- the same as https://github.com/web-infra-dev/rsbuild/pull/3790
> fix(rsbuild-plugin): failed to load remote modules with `server.base`

- apps/website-new/docs/en/guide/start/quick-start.mdx
Removed duplicate plugins property from the RSBuild config file to avoid redundancy.
> Removed duplicate plugins property from the rsbuild config

- .changeset/ai-lazy-tiger.md
- package.json
- packages/node/src/utils/hot-reload.ts
fix error caused by webpack module variables not allowing access to root cjs module constructor object
https://github.com/module-federation/core/issues/3115
> fix: do not crash if hmr fails

- .changeset/tricky-sheep-travel.md
- packages/rspack/src/ModuleFederationPlugin.ts
only patchChunkSplit when config set exposes
> fix(rspack): only patchChunkSplit when config set exposes

- apps/website-new/docs/en/plugin/plugins/retry-plugin.mdx
- apps/website-new/docs/zh/plugin/plugins/retry-plugin.mdx
chore: update retry-plugin docs chapter
> chore: update retry-plugin docs chapter

- packages/enhanced/src/lib/container/AsyncBoundaryPlugin.ts
- packages/enhanced/src/lib/container/ModuleFederationPlugin.ts
- packages/enhanced/src/lib/container/constant.ts
- packages/enhanced/src/lib/container/runtime/ChildCompilationRuntimePlugin.ts
- packages/enhanced/src/lib/container/runtime/EmbedFederationRuntimeModule.ts
- packages/enhanced/src/lib/container/runtime/FederationModulesPlugin.ts
- packages/enhanced/src/lib/container/runtime/FederationRuntimePlugin.ts
- packages/enhanced/src/lib/container/runtime/utils.ts
- packages/enhanced/src/lib/startup/StartupHelpers.ts
- packages/nextjs-mf/src/plugins/container/InvertedContainerRuntimeModule.ts
> chore: add license info

- .changeset/config.json
unlinking storybook addon from publish version sync as it will bump all to v3
> fix: unlink storybook addon from package publish

- .changeset/violet-fans-sleep.md
- apps/website-new/docs/en/plugin/plugins/retry-plugin.mdx
- packages/retry-plugin/__tests__/retry.spec.ts
- packages/retry-plugin/src/fetch-retry.ts
- packages/retry-plugin/src/types.d.ts
feat(retry-plugin): allow fallback function to receive failed URL
> feat(retry-plugin): allow fallback function to receive failed URL

- .changeset/cyan-emus-prove.md
- packages/runtime/src/global.ts
use [document.defaultView](https://developer.mozilla.org/en-US/docs/Web/API/Document/defaultView) to get real window object to solve csp issue
https://github.com/module-federation/core/pull/3108
> fix(runtime): use document.defaultView to get real window object to solve csp issue

- .changeset/little-insects-lick.md
- apps/website-new/docs/en/plugin/plugins/retry-plugin.mdx
- apps/website-new/docs/zh/plugin/plugins/retry-plugin.mdx
- packages/retry-plugin/src/fetch-retry.ts
- packages/retry-plugin/src/types.d.ts
fix: parameter url for fetch retry options should not be necessary
> fix: parameter url for fetch retry options should not be necessary

- .changeset/lucky-buckets-add.md
- packages/runtime/src/remote/index.ts
- packages/runtime/src/utils/load.ts
- packages/sdk/src/node.ts
- packages/sdk/src/types/hooks.ts
The pull request introduces changes to the runtime and SDK modules to allow for the passing of all loader hooks to the fetch and script functions. This provides more flexibility and control over the remote loading process, enabling developers to customize the fetch and script creation behavior using the provided hooks.
The key changes include:
- Updating the `RemoteHandler` class in the runtime module to accept a `loaderHook` parameter, which allows for passing all loader hooks to the `fetch` and `script` functions.
- Modifying the `loadEntryScript`, `loadEntryDom`, and `loadEntryNode` functions in the runtime utilities to accept a `loaderHook` parameter, enabling the passing of all loader hooks to the `fetch` and `script` functions.
- Adding a `loaderHook` parameter to the …
> feat(runtime): pass all loader hooks to the fetch and script functions

- .changeset/config.json
- .changeset/unlucky-cats-move.md
- packages/error-codes/package.json
- packages/error-codes/project.json
- packages/error-codes/rollup.config.js
> fix(error-codes): esm file should use .mjs ext

- .changeset/bright-guests-sip.md
- packages/runtime/__tests__/get-registered-share.spec.ts
- packages/runtime/src/utils/share.ts
use loaded or loading shared if sharedStrategy is loaded-first
https://github.com/module-federation/core/issues/3170
> fix(runtime): use loaded or loading shared if sharedStrategy is loaded-first

- apps/website-new/docs/en/guide/basic/_meta.json
- apps/website-new/docs/en/guide/basic/rspack.mdx
- apps/website-new/docs/zh/guide/basic/_meta.json
- apps/website-new/docs/zh/guide/basic/rspack.mdx
remove rsbuild plugin from rspack part
> docs: remove rsbuild plugin from rspack part

- .changeset/dry-bats-design.md
- packages/runtime/src/global.ts
- packages/runtime/src/remote/index.ts
use wrapper global instead of using globalThis directly to ensure legacy browser can use mf runtime as expected
https://github.com/web-infra-dev/rsbuild/issues/3593
> fix(runtime): use wrapper global instead of using globalThis directly

- .changeset/beige-cheetahs-tap.md
- packages/node/src/utils/hot-reload.ts
- packages/runtime/src/global.ts
- packages/runtime/src/helpers.ts
The bundler bundle GLOBAL_LOADING_REMOTE_ENTRY into share object closure ,and it can not access via globalThis . 
This PR aims to solve this issue and clear globalLoading internally in revalidate method.
https://github.com/module-federation/core/issues/3119
> fix: clear globalLoading cache in node env

- packages/sdk/README.md
update README.md to new createLogger API
> docs(sdk): update README to new createLogger API

- .changeset/fair-plums-live.md
- packages/dts-plugin/src/server/DevServer.ts
capture connection failure event, hold the broker server if the remote not start locally
https://github.com/module-federation/core/issues/3201
> fix(dts-plugin): hold the broker server if the remote not start locally

- packages/dts-plugin/src/server/DevServer.ts
log error if the code is not ETIMEDOUT
> chore(dts-plugin): log error if the code is not ETIMEDOUT

- .changeset/nervous-tomatoes-marry.md
- packages/runtime/src/core.ts
- packages/runtime/src/remote/index.ts
- packages/webpack-bundler-runtime/src/remotes.ts
When shareStrategy is 'version-first' , it should make sure the remote shareScopeMap have been registered yet . So it should call initializeSharing before executing loadRemote/loadShare
https://github.com/module-federation/core/issues/3209
> fix: call initializeSharing before load remote while shareStrategy is version first

- .changeset/tough-yaks-lay.md
- packages/managers/__tests__/SharedManager.spec.ts
- packages/managers/__tests__/__snapshots__/SharedManager.spec.ts.snap
- packages/managers/src/ContainerManager.ts
- packages/managers/src/PKGJsonManager.ts
- packages/managers/src/RemoteManager.ts
- packages/managers/src/SharedManager.ts
- packages/managers/tsconfig.json
* correct manifest shared configuration
* enable `noImplicitAny: true`
* add sharedManager.normalizedOptions test
https://github.com/module-federation/core/issues/3101
> fix(managers): correct manifest shared configuration

- .changeset/tender-insects-agree.md
- packages/modernjs/src/runtime/createRemoteSSRComponent.tsx
prevent components render multiple times if pops change
https://github.com/module-federation/module-federation-examples/issues/4298
> fix(modern-js-plugin): prevent components render multiple times if props change

- .changeset/fifty-flies-impress.md
- packages/storybook-addon/package.json
- packages/storybook-addon/src/lib/storybook-addon.ts
- pnpm-lock.yaml
- Mark Storybook 8 as valid peer dependencies as well.
- Loosen peer dep version restrictions of most of the peer deps.
- Add `@rsbuild/core` to peer deps.
- Mark all peer deps as optional.
- Run `pnpm dedupe` to clean the lock file.
https://github.com/rspack-contrib/storybook-rsbuild/issues/30#issuecomment-2470433081
> fix(storybook-addon): correct peerDependencies declaration

- .changeset/thick-baboons-hear.md
- packages/enhanced/src/lib/container/runtime/FederationRuntimePlugin.ts
This pull request removes the resolution of the runtime path with the .esm.mjs extension when the federation runtime is set to "hoisted" mode. This simplifies the runtime path handling and ensures that the correct runtime path is used in the application, improving the overall reliability and maintainability of the codebase.
https://github.com/module-federation/core/issues/3210
> fix(enhanced): remove resolve replacements

- .changeset/dirty-bikes-report.md
- .changeset/tasty-guests-shop.md
- packages/modernjs/package.json
- packages/modernjs/src/cli/utils.spec.ts
- packages/modernjs/src/cli/utils.ts
- packages/runtime/global.d.ts
- packages/runtime/src/utils/load.ts
* add define constant to help downgrade non-esm project
The magic comment([webpackIgnore](https://webpack.js.org/api/module-methods/#webpackignore)) will make rspack not downgrade the code , and [@rsbuild/plugin-check-syntax](https://github.com/rspack-contrib/rsbuild-plugin-check-syntax) will throw error . If users can make sure the project not use esm type module, they can set `FEDERATION_ALLOW_NEW_FUNCTION` by define plugin in build config , and skip the checker. 
reproduce repo: https://github.com/2heal1/rsbuild-demo/tree/chore/syntax-check
> fix(runtime): add define constant to help downgrade non-esm project

- .changeset/beige-terms-check.md
- packages/modernjs/src/cli/utils.ts
If user set watchOptions.ignored as regexp type , we should not handle it .
https://github.com/web-infra-dev/rsbuild/pull/4075
> fix: print warn if user set watchOptions.ignored value as regexp type

- .changeset/rude-berries-look.md
- apps/website-new/docs/en/practice/bridge/vue-bridge.mdx
- packages/bridge/vue3-bridge/src/create.ts
Added the ability to pass parameters to defineAsyncComponent, which solves the following issues: 
- Enables control over fallback components and their display parameters; 
- Improves compatibility with Nuxt by allowing configuration of the suspensible parameter; 
- Eliminates the package requirement to Configure your bundler to alias "vue" to "vue/dist/vue.esm-bundler.js".
Also updated the documentation, which was outdated even before my changes.
> feat(vue3-bridge): add support for passing parameters to defineAsyncComponent

- .changeset/beige-terms-check.md
- .changeset/fuzzy-dots-beam.md
- apps/modernjs-ssr/host/modern.config.ts
- apps/website-new/docs/en/guide/basic/type-prompt.mdx
- apps/website-new/docs/zh/guide/basic/type-prompt.mdx
- packages/modernjs/src/cli/configPlugin.ts
- packages/modernjs/src/cli/utils.spec.ts
- packages/modernjs/src/cli/utils.ts
- packages/modernjs/src/interfaces/bundler.ts
* override watchOptions.ignored if the modernjs internal value is regexp
* add `**/@my-types/**` to watchOptions.ignored if the value is string or string[]
https://github.com/web-infra-dev/rsbuild/pull/4075
> fix: override watchOptions.ignored if the modernjs internal value is regexp

- .changeset/great-pandas-shave.md
- packages/bridge/bridge-react/package.json
Before adapting react router v7, adjust the peer scope first.
https://github.com/module-federation/core/issues/3267
> chore(bridge-react): set react-router-dom peer version to >=4 <7

- .changeset/three-doors-bow.md
- packages/rspack/package.json
- packages/rspack/project.json
- packages/rspack/src/index.ts
Re-export inner plugins from rspack, to allow handling of cases like single runtime chunk where 2 containerPlugins need to be applied by user
https://github.com/module-federation/module-federation-examples/pull/4317
> fix(rspack): export container and container reference plugins

- apps/website-new/docs/en/plugin/dev/index.mdx
- packages/runtime/src/core.ts
The usage of the `fetch` hook was made official, therefore this PR adds documentation describing the usage including an example. It also removes an obsolete comment from `core.ts`.
https://github.com/module-federation/core/issues/3288
> docs: Add documentation for the manifest fetch hook

- .changeset/shaggy-ligers-teach.md
- packages/manifest/src/ManifestManager.ts
- packages/manifest/src/StatsManager.ts
the stats and manifest should both add `prefetchInterface` if enable `dataPrefetch`
> fix(manifest): stats should add prefetchInterface if enable dataPrefetch

- .changeset/real-otters-explode.md
- apps/website-new/docs/en/configure/dts.mdx
- packages/dts-plugin/src/core/lib/typeScriptCompiler.ts
- packages/sdk/src/types/plugins/ModuleFederationPlugin.ts
This PR adds a new property to the `dts` types that allows to pass a custom Current Work Directory to be used by `exec` to generate the types. It allows to generate types in environments where the user is running the plugin in a place where the Current Work Directory does not have Typescript installed.
#3338
> feat(dts-plugin): allow users to specify a `cwd` to generate the types

- .changeset/shy-snails-battle.md
- packages/enhanced/src/declarations/plugins/sharing/ProvideSharedPlugin.d.ts
- packages/enhanced/src/lib/sharing/ConsumeSharedModule.ts
- packages/enhanced/src/lib/sharing/ConsumeSharedPlugin.ts
- packages/enhanced/src/lib/sharing/ProvideSharedDependency.ts
- packages/enhanced/src/lib/sharing/ProvideSharedModule.ts
- packages/enhanced/src/lib/sharing/ProvideSharedPlugin.ts
- packages/enhanced/src/schemas/sharing/ProviderSharedPlugin.check.ts
- packages/enhanced/src/schemas/sharing/ProviderSharedPlugin.ts
- packages/enhanced/test/configCases/sharing/layers-provides-loader/.gitignore
- packages/enhanced/test/configCases/sharing/layers-provides-loader/loaders/different-layer-loader.js
- packages/enhanced/test/configCases/sharing/layers-provides-loader/loaders/explicit-layer-loader.js
- packages/enhanced/test/configCases/sharing/layers-provides-loader/loaders/multi-pkg-layer-loader.js
- packages/enhanced/test/configCases/sharing/layers-provides-loader/loaders/react-layer-loader.js
- packages/enhanced/test/configCases/sharing/layers-provides-loader/node_modules/lib2/index.js
- packages/enhanced/test/configCases/sharing/layers-provides-loader/node_modules/multi-pkg/thing1.js
- packages/enhanced/test/configCases/sharing/layers-provides-loader/node_modules/multi-pkg/thing2.js
- packages/enhanced/test/configCases/sharing/layers-provides-loader/node_modules/react/index.js
- packages/enhanced/test/configCases/sharing/layers-provides-loader/node_modules/react/index2.js
- packages/enhanced/test/configCases/sharing/layers-provides-loader/package.json
- packages/enhanced/test/configCases/sharing/layers-provides-loader/shared/react-boundary.js
- packages/enhanced/test/configCases/sharing/layers-provides-loader/src/index.js
- packages/enhanced/test/configCases/sharing/layers-provides-loader/test.config.js
- packages/enhanced/test/configCases/sharing/layers-provides-loader/tests/different-layers.test.js
- packages/enhanced/test/configCases/sharing/layers-provides-loader/tests/lib-two.test.js
- packages/enhanced/test/configCases/sharing/layers-provides-loader/tests/prefixed-share.test.js
- packages/enhanced/test/configCases/sharing/layers-provides-loader/tests/unlayered-share.test.js
- packages/enhanced/test/configCases/sharing/layers-provides-loader/webpack.config.js
This pull request introduces several enhancements to the shared module consumption and provisioning in the `packages/enhanced` library. The primary changes include adding support for a new `layer` property and improving the handling of configuration options.
* [`packages/enhanced/src/lib/sharing/ConsumeSharedPlugin.ts`](diffhunk://#diff-c97c2d9884d2a584a0dd77bf52955badffbbdbb18eda2eb243a76a1ed0f95d7dL69-R76): Updated the `createLookupKey` function to handle the new `layer` property in `contextInfo`.
* [`packages/enhanced/src/lib/sharing/ProvideSharedDependency.ts`](diffhunk://#diff-fe91d5cb298923919d62c517f55b34eeded48466fc43c39cb7482b1e11e85170R29): Added the `layer` property to the `ProvideSharedDependency` class and updated its methods to include `layer` information in identifiers and …
> feat(enhanced): ProvideSharedPlugin loader layer support

- .changeset/funny-drinks-bathe.md
- packages/runtime/src/remote/index.ts
remove duplicate registerRemotes warn
> chore(runtime): remove duplicate registerRemotes warn

- .changeset/six-yaks-teach.md
- packages/enhanced/src/rspack.ts
- packages/rspack/package.json
- packages/rspack/rollup.config.js
- packages/rspack/src/ModuleFederationPlugin.ts
enhanced import rspack plugin from `@module-federation/rspack/plugin` instead of `@module-federation/rspack` directly . 
Because the default `@module-federation/rspack` entry will export `rspack.container.ContainerPlugin` , but the `enhanced` or `modern-js-plugin` not install directly.
> fix(rspack): import plugin from sub path

- apps/website-new/docs/en/guide/basic/runtime.mdx
Updates the typescript definitions of the `init` function of Module Federation Runtime in the documentation site:
- `share.stategy` was deprecated in favor of to `shareStrategy` in https://github.com/module-federation/core/pull/2870 but the docs still referenced the old field
- The types for `ShareInfos` and `Shared` were actually only used in the `loadShare` function, not in the `init` function, but by being located in the init function it could cause confusion. They were moved.
https://github.com/module-federation/core/discussions/3340 (a discussion, not an issue)
> docs(runtime): update typescript definitions of init function

- apps/website-new/docs/en/plugin/plugins/retry-plugin.mdx
- corrects a typo in the documentation (script -> fetch).
- updates a section heading from Chinese to English (类型说明 -> Description).
- clarifies the default retryDelay of 1000ms.
> docs(retry-plugin): fix typo and clarify default retryDelay

- packages/retry-plugin/src/fetch-retry.ts
- packages/retry-plugin/src/util.ts
chore(retry-plugin): remove unnecessary null-check before calling beforeExecuteRetry
removes the unnecessary null-check before calling `beforeExecuteRetry()` since a default no-op function is already assigned.
> chore(retry-plugin): remove unnecessary null-check before calling beforeExecuteRetry

- .changeset/brave-boxes-remain.md
- packages/bridge/bridge-react/src/create.tsx
- packages/bridge/bridge-react/src/provider.tsx
- packages/bridge/bridge-react/src/remote/index.tsx
- packages/bridge/bridge-react/src/router-v5.tsx
- packages/bridge/bridge-react/src/router-v6.tsx
- packages/bridge/bridge-react/src/router.tsx
- packages/bridge/vue3-bridge/src/create.ts
- packages/bridge/vue3-bridge/src/provider.ts
- packages/bridge/vue3-bridge/src/remoteApp.tsx
fix(bridge-react): change all logs from info to debug in all bridge packages
Reproduce steps:
- Install and use @module-federation/bridge-react@0.8.1 package
https://github.com/module-federation/core/issues/3162
> fix(bridge-react): change all logs from info to debug in all bridge packages

- .changeset/angry-spoons-wink.md
- .changeset/spicy-roses-hear.md
- apps/rslib-module/.storybook/main.ts
- apps/rslib-module/package.json
- apps/rslib-module/rslib.config.ts
- packages/enhanced/src/index.ts
- packages/enhanced/src/rspack.ts
- packages/enhanced/src/webpack.ts
- packages/enhanced/src/wrapper/ModuleFederationPlugin.ts
- packages/modernjs/package.json
- packages/modernjs/src/cli/utils.ts
- packages/rsbuild-plugin/package.json
- packages/rsbuild-plugin/rollup.config.js
- packages/rsbuild-plugin/src/cli/index.ts
- packages/rsbuild-plugin/src/utils/autoDeleteSplitChunkCacheGroups.ts
- packages/rsbuild-plugin/src/utils/index.ts
- packages/rspack/src/ModuleFederationPlugin.ts
- packages/rspack/src/index.ts
- packages/storybook-addon/package.json
- packages/storybook-addon/preset.ts
- packages/storybook-addon/src/utils/with-module-federation-enhanced-rsbuild.ts
- pnpm-lock.yaml
split setUp function to help extend
> chore(rsbuild-plugin): split setUp function to help extend

- .changeset/metal-bags-admire.md
- packages/manifest/src/ModuleHandler.ts
- packages/manifest/src/StatsManager.ts
add default exposes fields if enable disableAssetsAnalyze
> fix(manifest): add default exposes fields if enable disableAssetsAnalyze

- .changeset/twelve-pumpkins-film.md
- apps/router-demo/router-host-2000/src/App.tsx
- packages/bridge/bridge-react/src/remote/index.tsx
feat(bridge-react): support basename passed by remote module props
> feat(bridge-react): support basename passed by remote module props

- .changeset/sour-carpets-walk.md
- apps/website-new/docs/en/guide/framework/modernjs.mdx
- apps/website-new/docs/zh/guide/framework/modernjs.mdx
- packages/modernjs/src/cli/configPlugin.ts
- packages/modernjs/src/cli/index.ts
- packages/modernjs/src/cli/ssrPlugin.ts
- packages/modernjs/src/types/index.ts
For projects with progressive migration, they may just want to use mf in csr not ssr .
> chore(modern-js-plugin): add disableSSR option

- .changeset/empty-steaks-appear.md
- apps/website-new/docs/en/configure/dts.mdx
- apps/website-new/docs/zh/configure/dts.mdx
- packages/dts-plugin/src/core/interfaces/DTSManagerOptions.ts
- packages/dts-plugin/src/core/lib/DTSManager.ts
- packages/dts-plugin/src/plugins/ConsumeTypesPlugin.ts
- packages/dts-plugin/src/plugins/DevPlugin.ts
- packages/dts-plugin/src/plugins/DtsPlugin.ts
- packages/dts-plugin/src/plugins/GenerateTypesPlugin.ts
- packages/manifest/src/StatsManager.ts
- packages/manifest/src/utils.ts
- packages/sdk/src/types/plugins/ModuleFederationPlugin.ts
add dts.displayErrorInTerminal to help control display error
> feat(dts-plugin): add dts.displayErrorInTerminal to help control display error

- apps/website-new/docs/zh/configure/experiments.mdx
chore: optimize the content of the experiments section
> chore: optimize the content of the experiments section

- apps/website-new/docs/en/practice/bridge/react-bridge.mdx
- apps/website-new/docs/en/practice/bridge/vue-bridge.mdx
- apps/website-new/docs/zh/practice/bridge/vue-bridge.mdx
chore: synchronize vue-bridge chinese and english documents
> chore: synchronize vue-bridge chinese and english documents

- .changeset/afraid-planets-juggle.md
- apps/router-demo/router-host-2000/src/App.tsx
- apps/router-demo/router-remote3-2003/src/App.vue
- apps/router-demo/router-remote3-2003/src/export-app.ts
- packages/bridge/vue3-bridge/src/provider.ts
fix(vue3-bridge): vue3-bridge parameter lossing issue
> fix(vue3-bridge): vue3-bridge parameter lossing issue

- .changeset/flat-olives-check.md
- packages/modernjs/src/cli/ssrPlugin.ts
Modern.js ssr plugin check enableSSR:
```
const enableSSR = pluginOptions.userConfig?.ssr === false ? false : Boolean(modernjsConfig?.server?.ssr);
```
> fix: enable SSR by utilizing pluginOptions and configuration

- apps/website-new/docs/zh/_meta.json
Add Nx and Zephyr Cloud link
Add Nx and Zephyr Cloud to 生态(Ecosystem) dropdown
> before
> after
> docs(website-new): add Nx and Zephyr Cloud link at zh-lang

- .changeset/cuddly-turkeys-cry.md
- apps/website-new/docs/en/guide/troubleshooting/type/TYPE-001.mdx
- apps/website-new/docs/zh/guide/troubleshooting/type/TYPE-001.mdx
- packages/dts-plugin/src/core/configurations/remotePlugin.test.ts
- packages/dts-plugin/src/core/configurations/remotePlugin.ts
- Enable tsc incremental build to reduce compile time.
- Add tip to disable type check
The following is a benchmark after enabling incremental build and noCheck in a real project with a large number of type errors
Since noCheck is only available in ts 5.5 and above, this pr only enables incremental by default.
```
hyperfine -i 'npx tsc --project tsconfig.nocheck.json' 'npx tsc --project tsconfig.incremental.json' 'npx tsc --project tsconfig.full.json' 'npx tsc --project tsconfig.base.json'
Benchmark 1: npx tsc --project tsconfig.nocheck.json
Time (mean ± σ):     16.692 s ±  4.414 s    [User: 18.791 s, System: 1.696 s]
Range (min … max):   14.638 s … 29.099 s    10 runs
Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet system without any …
```
> perf(dts-plugin): enable tsbuildinfo

- .changeset/sharp-pans-cheer.md
- packages/rsbuild-plugin/src/cli/index.ts
Add all `@module-federation/*` packages to `source.include` to avoid browser compatibility issues.
This change is to fix a syntax issue introduced in `@module-federation/webpack-bundler-runtime` in 0.9.1.
> https://github.com/web-infra-dev/rsbuild/actions/runs/13622050663/job/38073072909?pr=4690#step:7:920
> fix(rsbuild-plugin): add more MF packages to `source.include`

- .changeset/many-rings-compete.md
- packages/rsbuild-plugin/project.json
- packages/rsbuild-plugin/src/cli/index.spec.ts
- packages/rsbuild-plugin/src/cli/index.ts
- packages/rsbuild-plugin/vite.config.ts
update mf format judgment conditions
> chore(rsbuild-plugin): update mf format judgment conditions

- apps/website-new/docs/en/guide/framework/modernjs.mdx
For some reason syntax in the last code example wasn't correct highlighted. This PR fixes that problem.
> fix syntax highlight in modernjs.mdx

- .changeset/pink-rings-reply.md
- packages/modernjs/src/cli/configPlugin.ts
- packages/modernjs/src/cli/ssrPlugin.ts
- packages/modernjs/src/cli/utils.ts
- packages/modernjs/src/runtime/index.ts
- packages/runtime-core/src/plugins/generate-preload-assets.ts
preload filter loaded resources
> fix(runtime): preload filter loaded resources

- .changeset/shiny-geckos-switch.md
- apps/router-demo/router-remote3-2003/rsbuild.config.ts
- apps/router-demo/router-remote4-2004/rsbuild.config.ts
- packages/enhanced/src/lib/container/ModuleFederationPlugin.ts
- packages/rspack/package.json
- packages/rspack/rollup.config.js
- packages/rspack/src/ModuleFederationPlugin.ts
- packages/rspack/src/RemoteEntryPlugin.ts
- packages/runtime-plugins/inject-external-runtime-core-plugin/project.json
- pnpm-lock.yaml
rspack plugin support getPublicPath
> fix(rspack): support getPublicPath

- packages/bridge/bridge-react/package.json
Update peerDependency for react-router-dom to point to the version of React Router that is compatible with react-router-dom 7.
I did some tests and have already been using react-router-dom v7 with the Bridgea, and I haven't had any issues with the routing.
> fix(react-bridge): correct react-router-dom peer dependency

- apps/website-new/docs/en/guide/troubleshooting/type/TYPE-001.mdx
- apps/website-new/docs/zh/guide/troubleshooting/type/TYPE-001.mdx
optimize dts 001 error: delete cache dir first
> docs: optimize dts 001 error: delete cache dir first

- packages/node/package.json
- pnpm-lock.yaml
Add react 19 to the optional peer dependencies for the node package.
Also ran pnpm i to update the lock file.
Relates to some of the comments in https://github.com/module-federation/core/issues/3537
> chore(node): add react 19 to peer dependencies

- packages/node/package.json
- pnpm-lock.yaml
Fix the missing `|` for the react peer dependency in the node package.
https://github.com/module-federation/core/pull/3619
> fix(node): correct react peer dependency

- packages/rsbuild-plugin/src/cli/index.ts
Due to [security concerns](https://github.com/vitejs/vite/security/advisories/GHSA-vg6x-rcgg-rjx6), starting with Rsbuild >= 1.3.0, the Rsbuild dev server will no longer set `Access-Control-Allow-Origin` to `*` by default (https://github.com/web-infra-dev/rsbuild/pull/4876).
MF requires CORS headers, so I'll set that in `@module-federation/rsbuild-plugin`, which is the same as [other plugins](https://github.com/module-federation/core/blob/4b48eb5a03e71eba5e5a792f60b0b55e5e2f31a7/packages/modernjs/src/cli/configPlugin.ts#L84).
It's worth noting that in my opinion this is still a temporary solution, and we should try to avoid using `*` as the default value. A safer default value is needed instead.
> fix(rsbuild-plugin): explicitly setting CORS headers

- packages/bridge/vue3-bridge/package.json
- packages/bridge/vue3-bridge/vite.config.ts
The file extension in `"main"` in package.json needs to be `.cjs`
Change the output of the build for vue3-bridge to have:
```
dist/index.cjs
dist/index.js
```
instead of 
```
dist/index.cjs.js
dist/index.es.js
```
Change package.json to link to the changed filenames
https://github.com/module-federation/core/issues/3644
> fix(vue3-bridge): correct cjs build output file extension

- .changeset/serious-rules-shake.md
- packages/enhanced/src/lib/container/runtime/FederationRuntimePlugin.ts
This pull request includes a change to the `FederationRuntimePlugin` class in the `packages/enhanced/src/lib/container/runtime/FederationRuntimePlugin.ts` file. The most important change involves the removal of the `NormalModuleReplacementPlugin` setup.
Codebase simplification:
* [`packages/enhanced/src/lib/container/runtime/FederationRuntimePlugin.ts`](diffhunk://#diff-179f1bbf8541ac0e9d479ec019a6310ecfcf2a4af7a3c3624047b28eb611e54eL416-L428): Removed the setup for `NormalModuleReplacementPlugin` that was replacing the module federation runtime path based on the issuer context. This change simplifies the plugin application process and removes unnecessary complexity.
> fix(enhanced): remove normal module replacement of runtime

- .changeset/soft-islands-protect.md
- packages/modernjs/src/cli/ssrPlugin.ts
Some modernjs version may not apply rsbuild hook , if pass ssr.distOutputDir , apply it in bundlerChain hook first.
> fix(modern-js-plugin): apply ssr.distOutputDir in bundlerChain

- .changeset/green-countries-beg.md
- packages/manifest/src/StatsManager.ts
* correct shared assets 
* expose asstes filter shared assets
> fix(manifest): correct shared assets and filter expose assets

- .changeset/dull-buttons-sneeze.md
- packages/enhanced/src/lib/container/ModuleFederationPlugin.ts
- packages/rspack/src/ModuleFederationPlugin.ts
- packages/rspack/src/RemoteEntryPlugin.ts
- packages/rspack/src/logger.ts
apply getPublicPath only if exposes is set
> fix(enhanced): apply getPublicPath only if exposes is set

- .changeset/many-emus-shave.md
- apps/modernjs-ssr/dynamic-nested-remote/src/components/Content.tsx
- apps/modernjs-ssr/host/src/routes/all/page.tsx
- apps/modernjs-ssr/host/src/routes/dynamic-nested-remote/page.tsx
- apps/modernjs-ssr/host/src/routes/dynamic-remote/page.tsx
- apps/modernjs-ssr/host/src/routes/remote/page.tsx
- apps/modernjs-ssr/nested-remote/src/routes/page.tsx
- apps/website-new/docs/en/guide/framework/modernjs.mdx
- apps/website-new/docs/en/practice/frameworks/modern/dynamic-remote.mdx
- apps/website-new/docs/en/practice/frameworks/modern/index.mdx
- apps/website-new/docs/zh/guide/framework/modernjs.mdx
- apps/website-new/docs/zh/practice/frameworks/modern/dynamic-remote.mdx
- apps/website-new/docs/zh/practice/frameworks/modern/index.mdx
- packages/modernjs/src/cli/configPlugin.spec.ts
- packages/modernjs/src/cli/configPlugin.ts
- packages/modernjs/src/runtime/index.ts
- packages/modernjs/types.d.ts
* export kit namespace to prevent import react directly
* change the modernjs runtime import path from `@modern-js/runtime/mf ` to `@module-federation/modern-js/runtime`
before
```
import {
registerRemotes,
loadRemote,
createRemoteSSRComponent,
} from '@modern-js/runtime/mf';
```
after
```
import {
registerRemotes,
loadRemote,
kit,
} from '@module-federation/modern-js/runtime';
const { createRemoteSSRComponent } = kit;
```
https://github.com/web-infra-dev/modern.js/issues/7096
> fix(modern-js-plugin): export kit namespace to prevent import react directly

- .changeset/nice-windows-stare.md
- packages/rsbuild-plugin/src/cli/index.ts
* judge options from orignal userConfig
* wanring if not set server.cors.origin ( for most users , online consumer + local provider is quite normal , so need to set origin option to avoid cors )
> fix(rsbuild-plugin): judge options from orignal userConfig

- .changeset/brave-boats-tan.md
- .cursorignore
- .gitignore
- .vscode/launch.json
- .vscode/tasks.json
- packages/chrome-devtools/project.json
- packages/storybook-addon/package.json
This pull request introduces several updates aimed at improving development workflows, modernizing dependencies, and enhancing project configurations. The most significant changes include migrating from `npm` to `pnpm`, adding new debugging configurations, and updating build dependencies and tasks.
* Migrated all `npm` commands to `pnpm` in `.vscode/launch.json` to standardize the package manager across the project. This includes commands for running builds, tests, linting, and other tasks. Additionally, new debugging configurations (`Debug Enhanced Tests`, `Debug Current Test File`, `Debug Package Tests`, `Debug All Tests`) were added to streamline testing workflows.
* Introduced a new task in `.vscode/tasks.json` for building the `enhanced` package using `pnpm` and Node.js v18, with …
> chore: update ignores and tasks

- .changeset/quiet-bottles-unite.md
- packages/dts-plugin/src/plugins/DtsPlugin.ts
- packages/enhanced/src/lib/container/ModuleFederationPlugin.ts
- packages/rspack/src/ModuleFederationPlugin.ts
add dynamic-remote-type-hints-plugin to runtimePlugins if not disable
https://github.com/module-federation/core/issues/3737
> fix(dts-plugin): add dynamic-remote-type-hints-plugin to runtimePlugins if not disable

- .changeset/bright-beds-obey.md
- packages/runtime-core/src/utils/tool.ts
Currently, all remote entries must have `.json` or `.js` in their name - in RN & when working on MF in Metro, the output usually ends with `.bundle` and this limitation gets in the way in runtime. 
I'm marking this as a fix since there is no trace of having this as an actual requirement
n/a
> fix: allow extensions other than `.js` for non-manifest entries

- apps/website-new/docs/en/configure/experiments.mdx
This pull request updates the documentation for the `experiments` configuration in the `apps/website-new/docs/en/configure/experiments.mdx` file to provide clearer descriptions, additional warnings, and examples of how optimization flags impact bundle size. The most important changes include standardizing the formatting of configuration options, adding a warning about the `disableSnapshot` flag, and introducing a new table to illustrate the impact of optimization flags on `remoteEntry.js` size.
* Updated the description of the `experiments` configuration to clarify its purpose as enabling advanced and experimental capabilities in the plugin.
* Standardized the formatting of configuration option details (e.g., `Type`, `Required`, `Default`) for `asyncStartup`, `externalRuntime`, …
> docs(website-new): refactor experiments page for clarity, consistency

- apps/manifest-demo/webpack-host/runtimePlugin.ts
- apps/website-new/docs/en/guide/troubleshooting/other.mdx
- apps/website-new/docs/en/plugin/dev/index.mdx
- apps/website-new/docs/zh/guide/troubleshooting/other.mdx
- apps/website-new/docs/zh/plugin/dev/index.mdx
* Fix manifest demo preload test
* add createLink hook desc
* add preload failed with different credentials faq
> docs: add createLink hook desc and faq

- .changeset/silly-experts-begin.md
- packages/dts-plugin/src/core/lib/archiveHandler.test.ts
- packages/dts-plugin/src/core/lib/archiveHandler.ts
check types archive url and optimize the error msg
before
```
[ Module Federation DTS ] Failed to download /@mf-types.zip, you can set FEDERATION_DEBUG=true to see detail message. 
```
after
```
Failed to download types archive from "/@mf-types.zip". Set FEDERATION_DEBUG=true for details.
```
> chore(dts-plugin): check types archive url and optimize the error msg

- apps/website-new/docs/en/blog/error-load-remote.mdx
- apps/website-new/docs/zh/blog/error-load-remote.mdx
docs: remove invalid type(Manifest) import
> docs: remove invalid type(Manifest) import

- apps/website-new/docs/en/guide/basic/runtime.mdx
This fixes a minor formatting issue on the Federation Runtime docs where a brace isn't indented properly.
n/a
> docs(website-new): fix code formatting on Federation Runtime example

- .changeset/ninety-points-impress.md
- .changeset/sour-dragons-hang.md
- apps/node-host/webpack.config.js
- packages/modernjs/src/cli/configPlugin.ts
- packages/nextjs-mf/src/plugins/NextFederationPlugin/apply-server-plugins.ts
- packages/node/README.md
- packages/node/src/plugins/NodeFederationPlugin.ts
- packages/node/src/plugins/UniversalFederationPlugin.ts
- packages/rsbuild-plugin/src/utils/ssr.spec.ts
- packages/rsbuild-plugin/src/utils/ssr.ts
chunkhash can not guarantee filename the same and module id the same.
like below example
```diff
// build 1  a.7e6basdf1.js
exports.ids = ["3"]; exports.modules = {
- 7068:function(){} 
}
// build 2  a.7e6basdf1.js
exports.ids = ["3"]; exports.modules = {
+ 6262:function(){} 
}
```
and if hit the cdn catch, app will crash.
> fix(modern-js-plugin): use contenthash instead of chunkhash

- packages/rsbuild-plugin/package.json
- packages/rsbuild-plugin/rollup.config.js
Correct ESM output extension, without `type: "module"`, we must set the extension to `.mjs` to comply with the specifications of Node.js.
> fix(rsbuild-plugin): correct ESM output extension

- .changeset/tidy-foxes-fix.md
- packages/runtime-tools/package.json
This pull request includes a small change to the `packages/runtime-tools/package.json` file. The change specifies which files should be included during publishing by adding a `files` field with `dist/` and `README.md` listed.
> fix: set files on runtime-tools pkg

- apps/3000-home/package.json
- packages/enhanced/src/lib/sharing/ConsumeSharedPlugin.ts
- packages/enhanced/test/unit/sharing/ConsumeSharedPlugin.test.ts
- packages/managers/__tests__/__snapshots__/SharedManager.spec.ts.snap
- packages/sdk/src/node.ts
- pnpm-lock.yaml
This pull request enhances the `ConsumeSharedPlugin` class in `packages/enhanced/src/lib/sharing/ConsumeSharedPlugin.ts` by improving fallback logic for resolving shared module dependencies. The changes ensure that the plugin attempts to match unresolved dependencies with and without the `issuerLayer` context, increasing the robustness of dependency resolution.
* Updated the `match` variable to attempt resolution both with and without the `issuerLayer` context when looking up shared modules. This change ensures fallback behavior in case the `issuerLayer`-specific lookup fails.
* Improved the `moduleMatch` logic to include fallback resolution for module paths after `node_modules`, trying both with and without the `issuerLayer` context.
* Enhanced the `reconstructedMatch` logic to apply the …
> Share flalback

- .changeset/odd-walls-crash.md
- apps/website-new/docs/en/configure/dts.mdx
- packages/dts-plugin/src/core/configurations/hostPlugin.test.ts
- packages/dts-plugin/src/core/configurations/hostPlugin.ts
- packages/dts-plugin/src/core/lib/DTSManager.ts
- packages/dts-plugin/src/core/lib/archiveHandler.ts
- packages/dts-plugin/src/core/lib/utils.spec.ts
- packages/dts-plugin/src/core/lib/utils.ts
- packages/sdk/src/types/plugins/ModuleFederationPlugin.ts
Add option to change used IP family version
Fix #3382
> feat(dts-plugin): add `family` option

- packages/bridge/bridge-react/src/remote/component.tsx
- packages/bridge/bridge-react/src/remote/create.tsx
I've added loading prop inside the root div before the JSX will be rendered to avoid CLS issue
https://github.com/module-federation/core/issues/3974
> fix(bridge-react): Add loading in root component to avoid CLS problem

- .changeset/strange-years-cross.md
- packages/manifest/src/StatsManager.ts
Since Rspack support cache feature, the manifest should set `statsOptions.cacheModules` as `true` to collect cached modules, to prevent exposes resources be flushed when modifing code .
> fix: collect rspack cached modules in manifest

- .changeset/rare-laws-sleep.md
- packages/rsbuild-plugin/package.json
correct rsbuild plugin types field
> fix(rsbuild-plugin): invalid type field

- .github/workflows/preview.yml
- .github/workflows/release.yml
- packages/cli/package.json
- packages/rsbuild-plugin/package.json
1. enable trusted publishing for npm packages
2. Use pkg-pr-new to release preview version which will not leave useless preview version in npm versions
* https://github.blog/changelog/2025-07-31-npm-trusted-publishing-with-oidc-is-generally-available/
* https://docs.npmjs.com/trusted-publishers
* https://github.com/stackblitz-labs/pkg.pr.new
> chore: enable trusted publishing for npm packages

- .changeset/six-lies-hang.md
- packages/manifest/src/ModuleHandler.ts
- packages/manifest/src/StatsManager.ts
fix: the `exposes.requires` type in manifest.json should be array instead of object
> fix: the `exposes.requires` type in manifest.json should be array instead of object

- .changeset/wet-pants-sniff.md
- .github/workflows/build-and-test.yml
- .github/workflows/devtools.yml
- apps/3002-checkout/components/ButtonOldAnt.tsx
- apps/manifest-demo/3010-rspack-provider/src/components/ButtonOldAnt.tsx
- apps/manifest-demo/webpack-host/src/components/ButtonOldAnt.tsx
- apps/runtime-demo/3005-runtime-host/src/components/ButtonOldAnt.tsx
- apps/runtime-demo/3007-runtime-remote/src/components/ButtonOldAnt.tsx
- packages/cli/project.json
- packages/data-prefetch/project.json
- packages/error-codes/project.json
- packages/error-codes/rollup.config.js
- packages/managers/project.json
- packages/manifest/project.json
- packages/rsbuild-plugin/project.json
- packages/rspack/project.json
- packages/runtime-core/project.json
- packages/runtime-core/rollup.config.cjs
- packages/runtime-plugins/inject-external-runtime-core-plugin/project.json
- packages/runtime-tools/project.json
- packages/runtime/project.json
- packages/runtime/rollup.config.cjs
- packages/sdk/project.json
- packages/sdk/rollup.config.cjs
- packages/utilities/project.json
- packages/webpack-bundler-runtime/project.json
- packages/webpack-bundler-runtime/rollup.config.cjs
- remove the retry wrapper from the build-and-test workflow so affected tests run once with the existing timeout
- keep the Nx rollup packages on the tsc compiler and add sourcemap path transforms so the emitted maps line up with source files
- adjust old antd button demos to read the package version from the default JSON import, which works with the tsc build output
- add a changeset covering every package touched by the build config updates
- pnpm nx run manifest:build --skip-nx-cache
> chore: stabilize tsc rollup builds and clean up CI retries

- packages/enhanced/jest.config.ts
- packages/enhanced/src/lib/container/RemoteRuntimeModule.ts
- packages/enhanced/src/lib/container/runtime/FederationModulesPlugin.ts
- packages/enhanced/test/unit/container/FederationModulesPlugin.getCompilationHooks.test.ts
- packages/enhanced/test/unit/container/RemoteRuntimeModule.test.ts
- packages/enhanced/test/unit/sharing/resolveMatchedConfigs.test.ts
This PR improves test isolation and runtime compatibility in the enhanced package.
Changes:
- Enable `resetModules` in Jest config to isolate mocks per file.
- Preserve `remoteName` in `RemoteRuntimeModule` to support lazy remote update rebuilds via `updateRemoteOptions`.
- Duck-type the `Compilation` argument in `FederationModulesPlugin` to avoid cross-realm `instanceof` checks under VM modules (e.g., Jest with `--experimental-vm-modules`).
- Update VSCode launch configs for debugging package tests.
Verification:
- Ran `pnpm enhanced:jest` locally; 240 tests passed in ~33s with warmed Nx cache.
- No snapshot changes.
Notes:
- CI should run under Node 18 per engines; local runs under Node 24 also pass.
> fix(enhanced): isolate Jest modules and improve runtime compat
